// Generated by using Rcpp::compileAttributes() -> do not edit by hand
// Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#include <RcppArmadillo.h>
#include <Rcpp.h>

using namespace Rcpp;

#ifdef RCPP_USE_GLOBAL_ROSTREAM
Rcpp::Rostream<true>&  Rcpp::Rcout = Rcpp::Rcpp_cout_get();
Rcpp::Rostream<false>& Rcpp::Rcerr = Rcpp::Rcpp_cerr_get();
#endif

// fAICBIC
Rcpp::List fAICBIC(const arma::mat& y, int pmax, int c, Rcpp::Nullable<arma::mat> exog);
RcppExport SEXP _tidyMacro_fAICBIC(SEXP ySEXP, SEXP pmaxSEXP, SEXP cSEXP, SEXP exogSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< const arma::mat& >::type y(ySEXP);
    Rcpp::traits::input_parameter< int >::type pmax(pmaxSEXP);
    Rcpp::traits::input_parameter< int >::type c(cSEXP);
    Rcpp::traits::input_parameter< Rcpp::Nullable<arma::mat> >::type exog(exogSEXP);
    rcpp_result_gen = Rcpp::wrap(fAICBIC(y, pmax, c, exog));
    return rcpp_result_gen;
END_RCPP
}
// fBQIRF
arma::cube fBQIRF(const arma::cube& wold, const arma::mat& K, Rcpp::Nullable<arma::vec> scaling);
RcppExport SEXP _tidyMacro_fBQIRF(SEXP woldSEXP, SEXP KSEXP, SEXP scalingSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< const arma::cube& >::type wold(woldSEXP);
    Rcpp::traits::input_parameter< const arma::mat& >::type K(KSEXP);
    Rcpp::traits::input_parameter< Rcpp::Nullable<arma::vec> >::type scaling(scalingSEXP);
    rcpp_result_gen = Rcpp::wrap(fBQIRF(wold, K, scaling));
    return rcpp_result_gen;
END_RCPP
}
// fBootstrapBQ
Rcpp::List fBootstrapBQ(const arma::mat& y, const Rcpp::List& var_result, int nboot, int horizon, double prc, double prc2, const std::string& bootscheme, Rcpp::IntegerVector cumulate, Rcpp::Nullable<arma::vec> scaling, int n_threads);
RcppExport SEXP _tidyMacro_fBootstrapBQ(SEXP ySEXP, SEXP var_resultSEXP, SEXP nbootSEXP, SEXP horizonSEXP, SEXP prcSEXP, SEXP prc2SEXP, SEXP bootschemeSEXP, SEXP cumulateSEXP, SEXP scalingSEXP, SEXP n_threadsSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< const arma::mat& >::type y(ySEXP);
    Rcpp::traits::input_parameter< const Rcpp::List& >::type var_result(var_resultSEXP);
    Rcpp::traits::input_parameter< int >::type nboot(nbootSEXP);
    Rcpp::traits::input_parameter< int >::type horizon(horizonSEXP);
    Rcpp::traits::input_parameter< double >::type prc(prcSEXP);
    Rcpp::traits::input_parameter< double >::type prc2(prc2SEXP);
    Rcpp::traits::input_parameter< const std::string& >::type bootscheme(bootschemeSEXP);
    Rcpp::traits::input_parameter< Rcpp::IntegerVector >::type cumulate(cumulateSEXP);
    Rcpp::traits::input_parameter< Rcpp::Nullable<arma::vec> >::type scaling(scalingSEXP);
    Rcpp::traits::input_parameter< int >::type n_threads(n_threadsSEXP);
    rcpp_result_gen = Rcpp::wrap(fBootstrapBQ(y, var_result, nboot, horizon, prc, prc2, bootscheme, cumulate, scaling, n_threads));
    return rcpp_result_gen;
END_RCPP
}
// fBootstrapChol
Rcpp::List fBootstrapChol(const arma::mat& y, const Rcpp::List& var_result, int nboot, int horizon, double prc, double prc2, const std::string& bootscheme, Rcpp::Nullable<arma::mat> exog, int n_threads);
RcppExport SEXP _tidyMacro_fBootstrapChol(SEXP ySEXP, SEXP var_resultSEXP, SEXP nbootSEXP, SEXP horizonSEXP, SEXP prcSEXP, SEXP prc2SEXP, SEXP bootschemeSEXP, SEXP exogSEXP, SEXP n_threadsSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< const arma::mat& >::type y(ySEXP);
    Rcpp::traits::input_parameter< const Rcpp::List& >::type var_result(var_resultSEXP);
    Rcpp::traits::input_parameter< int >::type nboot(nbootSEXP);
    Rcpp::traits::input_parameter< int >::type horizon(horizonSEXP);
    Rcpp::traits::input_parameter< double >::type prc(prcSEXP);
    Rcpp::traits::input_parameter< double >::type prc2(prc2SEXP);
    Rcpp::traits::input_parameter< const std::string& >::type bootscheme(bootschemeSEXP);
    Rcpp::traits::input_parameter< Rcpp::Nullable<arma::mat> >::type exog(exogSEXP);
    Rcpp::traits::input_parameter< int >::type n_threads(n_threadsSEXP);
    rcpp_result_gen = Rcpp::wrap(fBootstrapChol(y, var_result, nboot, horizon, prc, prc2, bootscheme, exog, n_threads));
    return rcpp_result_gen;
END_RCPP
}
// fBootstrapCholCorrected
Rcpp::List fBootstrapCholCorrected(const arma::mat& y, const Rcpp::List& var_result, int nboot1, int nboot2, int horizon, double prc, double prc2, const std::string& bootscheme, Rcpp::Nullable<arma::mat> exog, int n_threads);
RcppExport SEXP _tidyMacro_fBootstrapCholCorrected(SEXP ySEXP, SEXP var_resultSEXP, SEXP nboot1SEXP, SEXP nboot2SEXP, SEXP horizonSEXP, SEXP prcSEXP, SEXP prc2SEXP, SEXP bootschemeSEXP, SEXP exogSEXP, SEXP n_threadsSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< const arma::mat& >::type y(ySEXP);
    Rcpp::traits::input_parameter< const Rcpp::List& >::type var_result(var_resultSEXP);
    Rcpp::traits::input_parameter< int >::type nboot1(nboot1SEXP);
    Rcpp::traits::input_parameter< int >::type nboot2(nboot2SEXP);
    Rcpp::traits::input_parameter< int >::type horizon(horizonSEXP);
    Rcpp::traits::input_parameter< double >::type prc(prcSEXP);
    Rcpp::traits::input_parameter< double >::type prc2(prc2SEXP);
    Rcpp::traits::input_parameter< const std::string& >::type bootscheme(bootschemeSEXP);
    Rcpp::traits::input_parameter< Rcpp::Nullable<arma::mat> >::type exog(exogSEXP);
    Rcpp::traits::input_parameter< int >::type n_threads(n_threadsSEXP);
    rcpp_result_gen = Rcpp::wrap(fBootstrapCholCorrected(y, var_result, nboot1, nboot2, horizon, prc, prc2, bootscheme, exog, n_threads));
    return rcpp_result_gen;
END_RCPP
}
// fBootstrapIVInvertible
Rcpp::List fBootstrapIVInvertible(const arma::mat& y, const arma::vec& instr, const Rcpp::List& var_result, int nboot, int p, int c, int hor, const arma::ivec& cumu, double prc, double prc2);
RcppExport SEXP _tidyMacro_fBootstrapIVInvertible(SEXP ySEXP, SEXP instrSEXP, SEXP var_resultSEXP, SEXP nbootSEXP, SEXP pSEXP, SEXP cSEXP, SEXP horSEXP, SEXP cumuSEXP, SEXP prcSEXP, SEXP prc2SEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< const arma::mat& >::type y(ySEXP);
    Rcpp::traits::input_parameter< const arma::vec& >::type instr(instrSEXP);
    Rcpp::traits::input_parameter< const Rcpp::List& >::type var_result(var_resultSEXP);
    Rcpp::traits::input_parameter< int >::type nboot(nbootSEXP);
    Rcpp::traits::input_parameter< int >::type p(pSEXP);
    Rcpp::traits::input_parameter< int >::type c(cSEXP);
    Rcpp::traits::input_parameter< int >::type hor(horSEXP);
    Rcpp::traits::input_parameter< const arma::ivec& >::type cumu(cumuSEXP);
    Rcpp::traits::input_parameter< double >::type prc(prcSEXP);
    Rcpp::traits::input_parameter< double >::type prc2(prc2SEXP);
    rcpp_result_gen = Rcpp::wrap(fBootstrapIVInvertible(y, instr, var_result, nboot, p, c, hor, cumu, prc, prc2));
    return rcpp_result_gen;
END_RCPP
}
// fBootstrapIVMBB
Rcpp::List fBootstrapIVMBB(const arma::mat& y, const Rcpp::List& var_result, const arma::mat& Z, int nboot, int blocksize, const arma::ivec& adjustZ, const arma::ivec& adjustu, int policyvar, int horizon, double prc, double prc2, Rcpp::Nullable<arma::mat> exog, int n_threads);
RcppExport SEXP _tidyMacro_fBootstrapIVMBB(SEXP ySEXP, SEXP var_resultSEXP, SEXP ZSEXP, SEXP nbootSEXP, SEXP blocksizeSEXP, SEXP adjustZSEXP, SEXP adjustuSEXP, SEXP policyvarSEXP, SEXP horizonSEXP, SEXP prcSEXP, SEXP prc2SEXP, SEXP exogSEXP, SEXP n_threadsSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< const arma::mat& >::type y(ySEXP);
    Rcpp::traits::input_parameter< const Rcpp::List& >::type var_result(var_resultSEXP);
    Rcpp::traits::input_parameter< const arma::mat& >::type Z(ZSEXP);
    Rcpp::traits::input_parameter< int >::type nboot(nbootSEXP);
    Rcpp::traits::input_parameter< int >::type blocksize(blocksizeSEXP);
    Rcpp::traits::input_parameter< const arma::ivec& >::type adjustZ(adjustZSEXP);
    Rcpp::traits::input_parameter< const arma::ivec& >::type adjustu(adjustuSEXP);
    Rcpp::traits::input_parameter< int >::type policyvar(policyvarSEXP);
    Rcpp::traits::input_parameter< int >::type horizon(horizonSEXP);
    Rcpp::traits::input_parameter< double >::type prc(prcSEXP);
    Rcpp::traits::input_parameter< double >::type prc2(prc2SEXP);
    Rcpp::traits::input_parameter< Rcpp::Nullable<arma::mat> >::type exog(exogSEXP);
    Rcpp::traits::input_parameter< int >::type n_threads(n_threadsSEXP);
    rcpp_result_gen = Rcpp::wrap(fBootstrapIVMBB(y, var_result, Z, nboot, blocksize, adjustZ, adjustu, policyvar, horizon, prc, prc2, exog, n_threads));
    return rcpp_result_gen;
END_RCPP
}
// fBootstrapIVRecover
Rcpp::List fBootstrapIVRecover(const arma::mat& y, const arma::vec& instr, const Rcpp::List& var_result, const arma::vec& noise, const arma::vec& delta, int nboot, int p, int c, int r, int hor, const arma::ivec& cumu, double prc, double prc2);
RcppExport SEXP _tidyMacro_fBootstrapIVRecover(SEXP ySEXP, SEXP instrSEXP, SEXP var_resultSEXP, SEXP noiseSEXP, SEXP deltaSEXP, SEXP nbootSEXP, SEXP pSEXP, SEXP cSEXP, SEXP rSEXP, SEXP horSEXP, SEXP cumuSEXP, SEXP prcSEXP, SEXP prc2SEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< const arma::mat& >::type y(ySEXP);
    Rcpp::traits::input_parameter< const arma::vec& >::type instr(instrSEXP);
    Rcpp::traits::input_parameter< const Rcpp::List& >::type var_result(var_resultSEXP);
    Rcpp::traits::input_parameter< const arma::vec& >::type noise(noiseSEXP);
    Rcpp::traits::input_parameter< const arma::vec& >::type delta(deltaSEXP);
    Rcpp::traits::input_parameter< int >::type nboot(nbootSEXP);
    Rcpp::traits::input_parameter< int >::type p(pSEXP);
    Rcpp::traits::input_parameter< int >::type c(cSEXP);
    Rcpp::traits::input_parameter< int >::type r(rSEXP);
    Rcpp::traits::input_parameter< int >::type hor(horSEXP);
    Rcpp::traits::input_parameter< const arma::ivec& >::type cumu(cumuSEXP);
    Rcpp::traits::input_parameter< double >::type prc(prcSEXP);
    Rcpp::traits::input_parameter< double >::type prc2(prc2SEXP);
    rcpp_result_gen = Rcpp::wrap(fBootstrapIVRecover(y, instr, var_result, noise, delta, nboot, p, c, r, hor, cumu, prc, prc2));
    return rcpp_result_gen;
END_RCPP
}
// fBootstrapMax
Rcpp::List fBootstrapMax(const arma::mat& y, const Rcpp::List& var_result, int nboot, int horizon, int var_idx, double prc, double prc2, Rcpp::IntegerVector cumulate, Rcpp::Nullable<arma::vec> scaling, Rcpp::Nullable<arma::mat> exog, int n_threads);
RcppExport SEXP _tidyMacro_fBootstrapMax(SEXP ySEXP, SEXP var_resultSEXP, SEXP nbootSEXP, SEXP horizonSEXP, SEXP var_idxSEXP, SEXP prcSEXP, SEXP prc2SEXP, SEXP cumulateSEXP, SEXP scalingSEXP, SEXP exogSEXP, SEXP n_threadsSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< const arma::mat& >::type y(ySEXP);
    Rcpp::traits::input_parameter< const Rcpp::List& >::type var_result(var_resultSEXP);
    Rcpp::traits::input_parameter< int >::type nboot(nbootSEXP);
    Rcpp::traits::input_parameter< int >::type horizon(horizonSEXP);
    Rcpp::traits::input_parameter< int >::type var_idx(var_idxSEXP);
    Rcpp::traits::input_parameter< double >::type prc(prcSEXP);
    Rcpp::traits::input_parameter< double >::type prc2(prc2SEXP);
    Rcpp::traits::input_parameter< Rcpp::IntegerVector >::type cumulate(cumulateSEXP);
    Rcpp::traits::input_parameter< Rcpp::Nullable<arma::vec> >::type scaling(scalingSEXP);
    Rcpp::traits::input_parameter< Rcpp::Nullable<arma::mat> >::type exog(exogSEXP);
    Rcpp::traits::input_parameter< int >::type n_threads(n_threadsSEXP);
    rcpp_result_gen = Rcpp::wrap(fBootstrapMax(y, var_result, nboot, horizon, var_idx, prc, prc2, cumulate, scaling, exog, n_threads));
    return rcpp_result_gen;
END_RCPP
}
// fBootstrapMaxCorrected
Rcpp::List fBootstrapMaxCorrected(const arma::mat& y, const Rcpp::List& var_result, int nboot1, int nboot2, int horizon, int var_idx, double prc, double prc2, Rcpp::IntegerVector cumulate, Rcpp::Nullable<arma::vec> scaling, Rcpp::Nullable<arma::mat> exog, int n_threads);
RcppExport SEXP _tidyMacro_fBootstrapMaxCorrected(SEXP ySEXP, SEXP var_resultSEXP, SEXP nboot1SEXP, SEXP nboot2SEXP, SEXP horizonSEXP, SEXP var_idxSEXP, SEXP prcSEXP, SEXP prc2SEXP, SEXP cumulateSEXP, SEXP scalingSEXP, SEXP exogSEXP, SEXP n_threadsSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< const arma::mat& >::type y(ySEXP);
    Rcpp::traits::input_parameter< const Rcpp::List& >::type var_result(var_resultSEXP);
    Rcpp::traits::input_parameter< int >::type nboot1(nboot1SEXP);
    Rcpp::traits::input_parameter< int >::type nboot2(nboot2SEXP);
    Rcpp::traits::input_parameter< int >::type horizon(horizonSEXP);
    Rcpp::traits::input_parameter< int >::type var_idx(var_idxSEXP);
    Rcpp::traits::input_parameter< double >::type prc(prcSEXP);
    Rcpp::traits::input_parameter< double >::type prc2(prc2SEXP);
    Rcpp::traits::input_parameter< Rcpp::IntegerVector >::type cumulate(cumulateSEXP);
    Rcpp::traits::input_parameter< Rcpp::Nullable<arma::vec> >::type scaling(scalingSEXP);
    Rcpp::traits::input_parameter< Rcpp::Nullable<arma::mat> >::type exog(exogSEXP);
    Rcpp::traits::input_parameter< int >::type n_threads(n_threadsSEXP);
    rcpp_result_gen = Rcpp::wrap(fBootstrapMaxCorrected(y, var_result, nboot1, nboot2, horizon, var_idx, prc, prc2, cumulate, scaling, exog, n_threads));
    return rcpp_result_gen;
END_RCPP
}
// fBootstrapUhlig
Rcpp::List fBootstrapUhlig(const arma::mat& y, const Rcpp::List& var_result, int nboot, int horizon, int idx, double prc, double prc2, Rcpp::IntegerVector cumulate, Rcpp::Nullable<arma::mat> exog, int n_threads);
RcppExport SEXP _tidyMacro_fBootstrapUhlig(SEXP ySEXP, SEXP var_resultSEXP, SEXP nbootSEXP, SEXP horizonSEXP, SEXP idxSEXP, SEXP prcSEXP, SEXP prc2SEXP, SEXP cumulateSEXP, SEXP exogSEXP, SEXP n_threadsSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< const arma::mat& >::type y(ySEXP);
    Rcpp::traits::input_parameter< const Rcpp::List& >::type var_result(var_resultSEXP);
    Rcpp::traits::input_parameter< int >::type nboot(nbootSEXP);
    Rcpp::traits::input_parameter< int >::type horizon(horizonSEXP);
    Rcpp::traits::input_parameter< int >::type idx(idxSEXP);
    Rcpp::traits::input_parameter< double >::type prc(prcSEXP);
    Rcpp::traits::input_parameter< double >::type prc2(prc2SEXP);
    Rcpp::traits::input_parameter< Rcpp::IntegerVector >::type cumulate(cumulateSEXP);
    Rcpp::traits::input_parameter< Rcpp::Nullable<arma::mat> >::type exog(exogSEXP);
    Rcpp::traits::input_parameter< int >::type n_threads(n_threadsSEXP);
    rcpp_result_gen = Rcpp::wrap(fBootstrapUhlig(y, var_result, nboot, horizon, idx, prc, prc2, cumulate, exog, n_threads));
    return rcpp_result_gen;
END_RCPP
}
// fBootstrapUhligCorrected
Rcpp::List fBootstrapUhligCorrected(const arma::mat& y, const Rcpp::List& var_result, int nboot1, int nboot2, int horizon, int idx, double prc, double prc2, Rcpp::IntegerVector cumulate, Rcpp::Nullable<arma::mat> exog, int n_threads);
RcppExport SEXP _tidyMacro_fBootstrapUhligCorrected(SEXP ySEXP, SEXP var_resultSEXP, SEXP nboot1SEXP, SEXP nboot2SEXP, SEXP horizonSEXP, SEXP idxSEXP, SEXP prcSEXP, SEXP prc2SEXP, SEXP cumulateSEXP, SEXP exogSEXP, SEXP n_threadsSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< const arma::mat& >::type y(ySEXP);
    Rcpp::traits::input_parameter< const Rcpp::List& >::type var_result(var_resultSEXP);
    Rcpp::traits::input_parameter< int >::type nboot1(nboot1SEXP);
    Rcpp::traits::input_parameter< int >::type nboot2(nboot2SEXP);
    Rcpp::traits::input_parameter< int >::type horizon(horizonSEXP);
    Rcpp::traits::input_parameter< int >::type idx(idxSEXP);
    Rcpp::traits::input_parameter< double >::type prc(prcSEXP);
    Rcpp::traits::input_parameter< double >::type prc2(prc2SEXP);
    Rcpp::traits::input_parameter< Rcpp::IntegerVector >::type cumulate(cumulateSEXP);
    Rcpp::traits::input_parameter< Rcpp::Nullable<arma::mat> >::type exog(exogSEXP);
    Rcpp::traits::input_parameter< int >::type n_threads(n_threadsSEXP);
    rcpp_result_gen = Rcpp::wrap(fBootstrapUhligCorrected(y, var_result, nboot1, nboot2, horizon, idx, prc, prc2, cumulate, exog, n_threads));
    return rcpp_result_gen;
END_RCPP
}
// fBootstrapVAR
Rcpp::List fBootstrapVAR(const arma::mat& y, const Rcpp::List& fVAR_result, const std::string& bootscheme);
RcppExport SEXP _tidyMacro_fBootstrapVAR(SEXP ySEXP, SEXP fVAR_resultSEXP, SEXP bootschemeSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< const arma::mat& >::type y(ySEXP);
    Rcpp::traits::input_parameter< const Rcpp::List& >::type fVAR_result(fVAR_resultSEXP);
    Rcpp::traits::input_parameter< const std::string& >::type bootscheme(bootschemeSEXP);
    rcpp_result_gen = Rcpp::wrap(fBootstrapVAR(y, fVAR_result, bootscheme));
    return rcpp_result_gen;
END_RCPP
}
// fCheckRestrictions
int fCheckRestrictions(const arma::cube& irf, int shock, const arma::rowvec& restr, const arma::uvec& hor_vec);
RcppExport SEXP _tidyMacro_fCheckRestrictions(SEXP irfSEXP, SEXP shockSEXP, SEXP restrSEXP, SEXP hor_vecSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< const arma::cube& >::type irf(irfSEXP);
    Rcpp::traits::input_parameter< int >::type shock(shockSEXP);
    Rcpp::traits::input_parameter< const arma::rowvec& >::type restr(restrSEXP);
    Rcpp::traits::input_parameter< const arma::uvec& >::type hor_vec(hor_vecSEXP);
    rcpp_result_gen = Rcpp::wrap(fCheckRestrictions(irf, shock, restr, hor_vec));
    return rcpp_result_gen;
END_RCPP
}
// fCholeskyIRF
arma::cube fCholeskyIRF(const arma::cube& wold, const arma::mat& S);
RcppExport SEXP _tidyMacro_fCholeskyIRF(SEXP woldSEXP, SEXP SSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< const arma::cube& >::type wold(woldSEXP);
    Rcpp::traits::input_parameter< const arma::mat& >::type S(SSEXP);
    rcpp_result_gen = Rcpp::wrap(fCholeskyIRF(wold, S));
    return rcpp_result_gen;
END_RCPP
}
// fCompanionMatrix
Rcpp::List fCompanionMatrix(arma::mat beta, int c, int p);
RcppExport SEXP _tidyMacro_fCompanionMatrix(SEXP betaSEXP, SEXP cSEXP, SEXP pSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< arma::mat >::type beta(betaSEXP);
    Rcpp::traits::input_parameter< int >::type c(cSEXP);
    Rcpp::traits::input_parameter< int >::type p(pSEXP);
    rcpp_result_gen = Rcpp::wrap(fCompanionMatrix(beta, c, p));
    return rcpp_result_gen;
END_RCPP
}
// fFEVDChol
Rcpp::List fFEVDChol(const arma::cube& chol_irf, int shock);
RcppExport SEXP _tidyMacro_fFEVDChol(SEXP chol_irfSEXP, SEXP shockSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< const arma::cube& >::type chol_irf(chol_irfSEXP);
    Rcpp::traits::input_parameter< int >::type shock(shockSEXP);
    rcpp_result_gen = Rcpp::wrap(fFEVDChol(chol_irf, shock));
    return rcpp_result_gen;
END_RCPP
}
// fFEVDIV
Rcpp::List fFEVDIV(arma::vec s, arma::mat S, arma::cube wold, int N, int hor, arma::mat sigma, arma::mat u, int T1, int p);
RcppExport SEXP _tidyMacro_fFEVDIV(SEXP sSEXP, SEXP SSEXP, SEXP woldSEXP, SEXP NSEXP, SEXP horSEXP, SEXP sigmaSEXP, SEXP uSEXP, SEXP T1SEXP, SEXP pSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< arma::vec >::type s(sSEXP);
    Rcpp::traits::input_parameter< arma::mat >::type S(SSEXP);
    Rcpp::traits::input_parameter< arma::cube >::type wold(woldSEXP);
    Rcpp::traits::input_parameter< int >::type N(NSEXP);
    Rcpp::traits::input_parameter< int >::type hor(horSEXP);
    Rcpp::traits::input_parameter< arma::mat >::type sigma(sigmaSEXP);
    Rcpp::traits::input_parameter< arma::mat >::type u(uSEXP);
    Rcpp::traits::input_parameter< int >::type T1(T1SEXP);
    Rcpp::traits::input_parameter< int >::type p(pSEXP);
    rcpp_result_gen = Rcpp::wrap(fFEVDIV(s, S, wold, N, hor, sigma, u, T1, p));
    return rcpp_result_gen;
END_RCPP
}
// fGenerateQ
arma::mat fGenerateQ(int N);
RcppExport SEXP _tidyMacro_fGenerateQ(SEXP NSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< int >::type N(NSEXP);
    rcpp_result_gen = Rcpp::wrap(fGenerateQ(N));
    return rcpp_result_gen;
END_RCPP
}
// fGenerateVARData
arma::mat fGenerateVARData(const arma::mat& y, int p, int c, const arma::mat& beta, const arma::mat& residuals);
RcppExport SEXP _tidyMacro_fGenerateVARData(SEXP ySEXP, SEXP pSEXP, SEXP cSEXP, SEXP betaSEXP, SEXP residualsSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< const arma::mat& >::type y(ySEXP);
    Rcpp::traits::input_parameter< int >::type p(pSEXP);
    Rcpp::traits::input_parameter< int >::type c(cSEXP);
    Rcpp::traits::input_parameter< const arma::mat& >::type beta(betaSEXP);
    Rcpp::traits::input_parameter< const arma::mat& >::type residuals(residualsSEXP);
    rcpp_result_gen = Rcpp::wrap(fGenerateVARData(y, p, c, beta, residuals));
    return rcpp_result_gen;
END_RCPP
}
// fGetBands
Rcpp::List fGetBands(const arma::cube& bootirf, double prc);
RcppExport SEXP _tidyMacro_fGetBands(SEXP bootirfSEXP, SEXP prcSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< const arma::cube& >::type bootirf(bootirfSEXP);
    Rcpp::traits::input_parameter< double >::type prc(prcSEXP);
    rcpp_result_gen = Rcpp::wrap(fGetBands(bootirf, prc));
    return rcpp_result_gen;
END_RCPP
}
// fGetShock
arma::vec fGetShock(const arma::mat& residuals, const arma::mat& sigma_full, const arma::vec& s, double shockSize, std::string normalize);
RcppExport SEXP _tidyMacro_fGetShock(SEXP residualsSEXP, SEXP sigma_fullSEXP, SEXP sSEXP, SEXP shockSizeSEXP, SEXP normalizeSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< const arma::mat& >::type residuals(residualsSEXP);
    Rcpp::traits::input_parameter< const arma::mat& >::type sigma_full(sigma_fullSEXP);
    Rcpp::traits::input_parameter< const arma::vec& >::type s(sSEXP);
    Rcpp::traits::input_parameter< double >::type shockSize(shockSizeSEXP);
    Rcpp::traits::input_parameter< std::string >::type normalize(normalizeSEXP);
    rcpp_result_gen = Rcpp::wrap(fGetShock(residuals, sigma_full, s, shockSize, normalize));
    return rcpp_result_gen;
END_RCPP
}
// fHDIV
Rcpp::List fHDIV(const arma::mat& residuals, const arma::mat& sigma, const arma::vec& s, const arma::mat& beta, int c, int p);
RcppExport SEXP _tidyMacro_fHDIV(SEXP residualsSEXP, SEXP sigmaSEXP, SEXP sSEXP, SEXP betaSEXP, SEXP cSEXP, SEXP pSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< const arma::mat& >::type residuals(residualsSEXP);
    Rcpp::traits::input_parameter< const arma::mat& >::type sigma(sigmaSEXP);
    Rcpp::traits::input_parameter< const arma::vec& >::type s(sSEXP);
    Rcpp::traits::input_parameter< const arma::mat& >::type beta(betaSEXP);
    Rcpp::traits::input_parameter< int >::type c(cSEXP);
    Rcpp::traits::input_parameter< int >::type p(pSEXP);
    rcpp_result_gen = Rcpp::wrap(fHDIV(residuals, sigma, s, beta, c, p));
    return rcpp_result_gen;
END_RCPP
}
// fBootstrapHDIV
Rcpp::List fBootstrapHDIV(const arma::mat& y, const Rcpp::List& var_result, const arma::mat& Z, const arma::vec& s, int nboot, int blocksize, const arma::ivec& adjustZ, const arma::ivec& adjustu, int policyvar, double prc, int n_threads);
RcppExport SEXP _tidyMacro_fBootstrapHDIV(SEXP ySEXP, SEXP var_resultSEXP, SEXP ZSEXP, SEXP sSEXP, SEXP nbootSEXP, SEXP blocksizeSEXP, SEXP adjustZSEXP, SEXP adjustuSEXP, SEXP policyvarSEXP, SEXP prcSEXP, SEXP n_threadsSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< const arma::mat& >::type y(ySEXP);
    Rcpp::traits::input_parameter< const Rcpp::List& >::type var_result(var_resultSEXP);
    Rcpp::traits::input_parameter< const arma::mat& >::type Z(ZSEXP);
    Rcpp::traits::input_parameter< const arma::vec& >::type s(sSEXP);
    Rcpp::traits::input_parameter< int >::type nboot(nbootSEXP);
    Rcpp::traits::input_parameter< int >::type blocksize(blocksizeSEXP);
    Rcpp::traits::input_parameter< const arma::ivec& >::type adjustZ(adjustZSEXP);
    Rcpp::traits::input_parameter< const arma::ivec& >::type adjustu(adjustuSEXP);
    Rcpp::traits::input_parameter< int >::type policyvar(policyvarSEXP);
    Rcpp::traits::input_parameter< double >::type prc(prcSEXP);
    Rcpp::traits::input_parameter< int >::type n_threads(n_threadsSEXP);
    rcpp_result_gen = Rcpp::wrap(fBootstrapHDIV(y, var_result, Z, s, nboot, blocksize, adjustZ, adjustu, policyvar, prc, n_threads));
    return rcpp_result_gen;
END_RCPP
}
// fHeteroIRF
Rcpp::List fHeteroIRF(const Rcpp::List& var_result, const arma::mat& Z, const arma::ivec& adjustu, const arma::ivec& indsR1, int hor, int nvar, double scale);
RcppExport SEXP _tidyMacro_fHeteroIRF(SEXP var_resultSEXP, SEXP ZSEXP, SEXP adjustuSEXP, SEXP indsR1SEXP, SEXP horSEXP, SEXP nvarSEXP, SEXP scaleSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< const Rcpp::List& >::type var_result(var_resultSEXP);
    Rcpp::traits::input_parameter< const arma::mat& >::type Z(ZSEXP);
    Rcpp::traits::input_parameter< const arma::ivec& >::type adjustu(adjustuSEXP);
    Rcpp::traits::input_parameter< const arma::ivec& >::type indsR1(indsR1SEXP);
    Rcpp::traits::input_parameter< int >::type hor(horSEXP);
    Rcpp::traits::input_parameter< int >::type nvar(nvarSEXP);
    Rcpp::traits::input_parameter< double >::type scale(scaleSEXP);
    rcpp_result_gen = Rcpp::wrap(fHeteroIRF(var_result, Z, adjustu, indsR1, hor, nvar, scale));
    return rcpp_result_gen;
END_RCPP
}
// fBootstrapHetero
Rcpp::List fBootstrapHetero(const arma::mat& y, const Rcpp::List& var_result, const arma::mat& Z, const arma::ivec& indsR1, const arma::ivec& adjustu, int nboot, int blocksize, int hor, int nvar, double scale, double prc, double prc2, int n_threads);
RcppExport SEXP _tidyMacro_fBootstrapHetero(SEXP ySEXP, SEXP var_resultSEXP, SEXP ZSEXP, SEXP indsR1SEXP, SEXP adjustuSEXP, SEXP nbootSEXP, SEXP blocksizeSEXP, SEXP horSEXP, SEXP nvarSEXP, SEXP scaleSEXP, SEXP prcSEXP, SEXP prc2SEXP, SEXP n_threadsSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< const arma::mat& >::type y(ySEXP);
    Rcpp::traits::input_parameter< const Rcpp::List& >::type var_result(var_resultSEXP);
    Rcpp::traits::input_parameter< const arma::mat& >::type Z(ZSEXP);
    Rcpp::traits::input_parameter< const arma::ivec& >::type indsR1(indsR1SEXP);
    Rcpp::traits::input_parameter< const arma::ivec& >::type adjustu(adjustuSEXP);
    Rcpp::traits::input_parameter< int >::type nboot(nbootSEXP);
    Rcpp::traits::input_parameter< int >::type blocksize(blocksizeSEXP);
    Rcpp::traits::input_parameter< int >::type hor(horSEXP);
    Rcpp::traits::input_parameter< int >::type nvar(nvarSEXP);
    Rcpp::traits::input_parameter< double >::type scale(scaleSEXP);
    Rcpp::traits::input_parameter< double >::type prc(prcSEXP);
    Rcpp::traits::input_parameter< double >::type prc2(prc2SEXP);
    Rcpp::traits::input_parameter< int >::type n_threads(n_threadsSEXP);
    rcpp_result_gen = Rcpp::wrap(fBootstrapHetero(y, var_result, Z, indsR1, adjustu, nboot, blocksize, hor, nvar, scale, prc, prc2, n_threads));
    return rcpp_result_gen;
END_RCPP
}
// fHistDec
Rcpp::List fHistDec(const arma::mat& y, const Rcpp::List& fVAR, const arma::mat& K, int series);
RcppExport SEXP _tidyMacro_fHistDec(SEXP ySEXP, SEXP fVARSEXP, SEXP KSEXP, SEXP seriesSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< const arma::mat& >::type y(ySEXP);
    Rcpp::traits::input_parameter< const Rcpp::List& >::type fVAR(fVARSEXP);
    Rcpp::traits::input_parameter< const arma::mat& >::type K(KSEXP);
    Rcpp::traits::input_parameter< int >::type series(seriesSEXP);
    rcpp_result_gen = Rcpp::wrap(fHistDec(y, fVAR, K, series));
    return rcpp_result_gen;
END_RCPP
}
// fLP_cpp
Rcpp::List fLP_cpp(const arma::mat& Y, const arma::mat& X, int H, int shock_col, double conf_level, int nw_lags_base, bool store_full, bool cumulative, int n_threads, int nw_offset, bool verbose, Rcpp::Nullable<arma::mat> Y_pre);
RcppExport SEXP _tidyMacro_fLP_cpp(SEXP YSEXP, SEXP XSEXP, SEXP HSEXP, SEXP shock_colSEXP, SEXP conf_levelSEXP, SEXP nw_lags_baseSEXP, SEXP store_fullSEXP, SEXP cumulativeSEXP, SEXP n_threadsSEXP, SEXP nw_offsetSEXP, SEXP verboseSEXP, SEXP Y_preSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< const arma::mat& >::type Y(YSEXP);
    Rcpp::traits::input_parameter< const arma::mat& >::type X(XSEXP);
    Rcpp::traits::input_parameter< int >::type H(HSEXP);
    Rcpp::traits::input_parameter< int >::type shock_col(shock_colSEXP);
    Rcpp::traits::input_parameter< double >::type conf_level(conf_levelSEXP);
    Rcpp::traits::input_parameter< int >::type nw_lags_base(nw_lags_baseSEXP);
    Rcpp::traits::input_parameter< bool >::type store_full(store_fullSEXP);
    Rcpp::traits::input_parameter< bool >::type cumulative(cumulativeSEXP);
    Rcpp::traits::input_parameter< int >::type n_threads(n_threadsSEXP);
    Rcpp::traits::input_parameter< int >::type nw_offset(nw_offsetSEXP);
    Rcpp::traits::input_parameter< bool >::type verbose(verboseSEXP);
    Rcpp::traits::input_parameter< Rcpp::Nullable<arma::mat> >::type Y_pre(Y_preSEXP);
    rcpp_result_gen = Rcpp::wrap(fLP_cpp(Y, X, H, shock_col, conf_level, nw_lags_base, store_full, cumulative, n_threads, nw_offset, verbose, Y_pre));
    return rcpp_result_gen;
END_RCPP
}
// fLPDID_cpp
Rcpp::List fLPDID_cpp(const arma::vec& y, const arma::vec& treat, const arma::mat& X, const arma::ivec& i_index, const arma::ivec& t_index, const arma::ivec& cl_index, int pre_window, int post_window, bool nonabsorbing, int Lwin, int ccc, bool pmd, bool reweight, int n_threads, bool verbose);
RcppExport SEXP _tidyMacro_fLPDID_cpp(SEXP ySEXP, SEXP treatSEXP, SEXP XSEXP, SEXP i_indexSEXP, SEXP t_indexSEXP, SEXP cl_indexSEXP, SEXP pre_windowSEXP, SEXP post_windowSEXP, SEXP nonabsorbingSEXP, SEXP LwinSEXP, SEXP cccSEXP, SEXP pmdSEXP, SEXP reweightSEXP, SEXP n_threadsSEXP, SEXP verboseSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< const arma::vec& >::type y(ySEXP);
    Rcpp::traits::input_parameter< const arma::vec& >::type treat(treatSEXP);
    Rcpp::traits::input_parameter< const arma::mat& >::type X(XSEXP);
    Rcpp::traits::input_parameter< const arma::ivec& >::type i_index(i_indexSEXP);
    Rcpp::traits::input_parameter< const arma::ivec& >::type t_index(t_indexSEXP);
    Rcpp::traits::input_parameter< const arma::ivec& >::type cl_index(cl_indexSEXP);
    Rcpp::traits::input_parameter< int >::type pre_window(pre_windowSEXP);
    Rcpp::traits::input_parameter< int >::type post_window(post_windowSEXP);
    Rcpp::traits::input_parameter< bool >::type nonabsorbing(nonabsorbingSEXP);
    Rcpp::traits::input_parameter< int >::type Lwin(LwinSEXP);
    Rcpp::traits::input_parameter< int >::type ccc(cccSEXP);
    Rcpp::traits::input_parameter< bool >::type pmd(pmdSEXP);
    Rcpp::traits::input_parameter< bool >::type reweight(reweightSEXP);
    Rcpp::traits::input_parameter< int >::type n_threads(n_threadsSEXP);
    Rcpp::traits::input_parameter< bool >::type verbose(verboseSEXP);
    rcpp_result_gen = Rcpp::wrap(fLPDID_cpp(y, treat, X, i_index, t_index, cl_index, pre_window, post_window, nonabsorbing, Lwin, ccc, pmd, reweight, n_threads, verbose));
    return rcpp_result_gen;
END_RCPP
}
// fLPIV_cpp
Rcpp::List fLPIV_cpp(const arma::mat& Y, const arma::vec& D, const arma::mat& Z, const arma::mat& C, int H, double conf_level, int nw_lags_iv, bool cumulative, int n_threads, bool verbose, Rcpp::Nullable<arma::mat> Y_pre);
RcppExport SEXP _tidyMacro_fLPIV_cpp(SEXP YSEXP, SEXP DSEXP, SEXP ZSEXP, SEXP CSEXP, SEXP HSEXP, SEXP conf_levelSEXP, SEXP nw_lags_ivSEXP, SEXP cumulativeSEXP, SEXP n_threadsSEXP, SEXP verboseSEXP, SEXP Y_preSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< const arma::mat& >::type Y(YSEXP);
    Rcpp::traits::input_parameter< const arma::vec& >::type D(DSEXP);
    Rcpp::traits::input_parameter< const arma::mat& >::type Z(ZSEXP);
    Rcpp::traits::input_parameter< const arma::mat& >::type C(CSEXP);
    Rcpp::traits::input_parameter< int >::type H(HSEXP);
    Rcpp::traits::input_parameter< double >::type conf_level(conf_levelSEXP);
    Rcpp::traits::input_parameter< int >::type nw_lags_iv(nw_lags_ivSEXP);
    Rcpp::traits::input_parameter< bool >::type cumulative(cumulativeSEXP);
    Rcpp::traits::input_parameter< int >::type n_threads(n_threadsSEXP);
    Rcpp::traits::input_parameter< bool >::type verbose(verboseSEXP);
    Rcpp::traits::input_parameter< Rcpp::Nullable<arma::mat> >::type Y_pre(Y_preSEXP);
    rcpp_result_gen = Rcpp::wrap(fLPIV_cpp(Y, D, Z, C, H, conf_level, nw_lags_iv, cumulative, n_threads, verbose, Y_pre));
    return rcpp_result_gen;
END_RCPP
}
// fLPPanel_cpp
Rcpp::List fLPPanel_cpp(const arma::mat& y, const arma::mat& s, const arma::mat& X, const arma::mat& W, const arma::imat& FE, const arma::ivec& i_index, const arma::ivec& t_index, int H, int p_max, bool small_sample, bool cumulative, int n_threads, bool verbose);
RcppExport SEXP _tidyMacro_fLPPanel_cpp(SEXP ySEXP, SEXP sSEXP, SEXP XSEXP, SEXP WSEXP, SEXP FESEXP, SEXP i_indexSEXP, SEXP t_indexSEXP, SEXP HSEXP, SEXP p_maxSEXP, SEXP small_sampleSEXP, SEXP cumulativeSEXP, SEXP n_threadsSEXP, SEXP verboseSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< const arma::mat& >::type y(ySEXP);
    Rcpp::traits::input_parameter< const arma::mat& >::type s(sSEXP);
    Rcpp::traits::input_parameter< const arma::mat& >::type X(XSEXP);
    Rcpp::traits::input_parameter< const arma::mat& >::type W(WSEXP);
    Rcpp::traits::input_parameter< const arma::imat& >::type FE(FESEXP);
    Rcpp::traits::input_parameter< const arma::ivec& >::type i_index(i_indexSEXP);
    Rcpp::traits::input_parameter< const arma::ivec& >::type t_index(t_indexSEXP);
    Rcpp::traits::input_parameter< int >::type H(HSEXP);
    Rcpp::traits::input_parameter< int >::type p_max(p_maxSEXP);
    Rcpp::traits::input_parameter< bool >::type small_sample(small_sampleSEXP);
    Rcpp::traits::input_parameter< bool >::type cumulative(cumulativeSEXP);
    Rcpp::traits::input_parameter< int >::type n_threads(n_threadsSEXP);
    Rcpp::traits::input_parameter< bool >::type verbose(verboseSEXP);
    rcpp_result_gen = Rcpp::wrap(fLPPanel_cpp(y, s, X, W, FE, i_index, t_index, H, p_max, small_sample, cumulative, n_threads, verbose));
    return rcpp_result_gen;
END_RCPP
}
// fLagMakerMatrix
arma::mat fLagMakerMatrix(arma::mat y, int p);
RcppExport SEXP _tidyMacro_fLagMakerMatrix(SEXP ySEXP, SEXP pSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< arma::mat >::type y(ySEXP);
    Rcpp::traits::input_parameter< int >::type p(pSEXP);
    rcpp_result_gen = Rcpp::wrap(fLagMakerMatrix(y, p));
    return rcpp_result_gen;
END_RCPP
}
// fMBBVAR
Rcpp::List fMBBVAR(const arma::mat& eps, int lags, int BlockSize, Rcpp::Nullable<arma::mat> M);
RcppExport SEXP _tidyMacro_fMBBVAR(SEXP epsSEXP, SEXP lagsSEXP, SEXP BlockSizeSEXP, SEXP MSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< const arma::mat& >::type eps(epsSEXP);
    Rcpp::traits::input_parameter< int >::type lags(lagsSEXP);
    Rcpp::traits::input_parameter< int >::type BlockSize(BlockSizeSEXP);
    Rcpp::traits::input_parameter< Rcpp::Nullable<arma::mat> >::type M(MSEXP);
    rcpp_result_gen = Rcpp::wrap(fMBBVAR(eps, lags, BlockSize, M));
    return rcpp_result_gen;
END_RCPP
}
// fMSW
Rcpp::List fMSW(const Rcpp::List& var_result, const arma::mat& Z, const arma::mat& finaldata, const arma::ivec& adjustu, int hor, int nvar, double scale, double confidence, int NWlags);
RcppExport SEXP _tidyMacro_fMSW(SEXP var_resultSEXP, SEXP ZSEXP, SEXP finaldataSEXP, SEXP adjustuSEXP, SEXP horSEXP, SEXP nvarSEXP, SEXP scaleSEXP, SEXP confidenceSEXP, SEXP NWlagsSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< const Rcpp::List& >::type var_result(var_resultSEXP);
    Rcpp::traits::input_parameter< const arma::mat& >::type Z(ZSEXP);
    Rcpp::traits::input_parameter< const arma::mat& >::type finaldata(finaldataSEXP);
    Rcpp::traits::input_parameter< const arma::ivec& >::type adjustu(adjustuSEXP);
    Rcpp::traits::input_parameter< int >::type hor(horSEXP);
    Rcpp::traits::input_parameter< int >::type nvar(nvarSEXP);
    Rcpp::traits::input_parameter< double >::type scale(scaleSEXP);
    Rcpp::traits::input_parameter< double >::type confidence(confidenceSEXP);
    Rcpp::traits::input_parameter< int >::type NWlags(NWlagsSEXP);
    rcpp_result_gen = Rcpp::wrap(fMSW(var_result, Z, finaldata, adjustu, hor, nvar, scale, confidence, NWlags));
    return rcpp_result_gen;
END_RCPP
}
// fMaxIRF
arma::mat fMaxIRF(const arma::cube& wold, const arma::mat& S, int var_idx);
RcppExport SEXP _tidyMacro_fMaxIRF(SEXP woldSEXP, SEXP SSEXP, SEXP var_idxSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< const arma::cube& >::type wold(woldSEXP);
    Rcpp::traits::input_parameter< const arma::mat& >::type S(SSEXP);
    Rcpp::traits::input_parameter< int >::type var_idx(var_idxSEXP);
    rcpp_result_gen = Rcpp::wrap(fMaxIRF(wold, S, var_idx));
    return rcpp_result_gen;
END_RCPP
}
// fOLS
Rcpp::List fOLS(arma::mat y, arma::mat X, int c, int lag);
RcppExport SEXP _tidyMacro_fOLS(SEXP ySEXP, SEXP XSEXP, SEXP cSEXP, SEXP lagSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< arma::mat >::type y(ySEXP);
    Rcpp::traits::input_parameter< arma::mat >::type X(XSEXP);
    Rcpp::traits::input_parameter< int >::type c(cSEXP);
    Rcpp::traits::input_parameter< int >::type lag(lagSEXP);
    rcpp_result_gen = Rcpp::wrap(fOLS(y, X, c, lag));
    return rcpp_result_gen;
END_RCPP
}
// fPolyConvolve
arma::cube fPolyConvolve(const arma::cube& A, const arma::cube& B, int nlags);
RcppExport SEXP _tidyMacro_fPolyConvolve(SEXP ASEXP, SEXP BSEXP, SEXP nlagsSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< const arma::cube& >::type A(ASEXP);
    Rcpp::traits::input_parameter< const arma::cube& >::type B(BSEXP);
    Rcpp::traits::input_parameter< int >::type nlags(nlagsSEXP);
    rcpp_result_gen = Rcpp::wrap(fPolyConvolve(A, B, nlags));
    return rcpp_result_gen;
END_RCPP
}
// fRemoveBias
Rcpp::List fRemoveBias(const arma::mat& beta, int c, int p, const arma::cube& boot_beta);
RcppExport SEXP _tidyMacro_fRemoveBias(SEXP betaSEXP, SEXP cSEXP, SEXP pSEXP, SEXP boot_betaSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< const arma::mat& >::type beta(betaSEXP);
    Rcpp::traits::input_parameter< int >::type c(cSEXP);
    Rcpp::traits::input_parameter< int >::type p(pSEXP);
    Rcpp::traits::input_parameter< const arma::cube& >::type boot_beta(boot_betaSEXP);
    rcpp_result_gen = Rcpp::wrap(fRemoveBias(beta, c, p, boot_beta));
    return rcpp_result_gen;
END_RCPP
}
// fSVARSteps
void fSVARSteps();
RcppExport SEXP _tidyMacro_fSVARSteps() {
BEGIN_RCPP
    Rcpp::RNGScope rcpp_rngScope_gen;
    fSVARSteps();
    return R_NilValue;
END_RCPP
}
// fSpectralFEVD
arma::vec fSpectralFEVD(const arma::cube& D, const arma::mat& irf_s, const arma::vec& band, int J, bool fourier);
RcppExport SEXP _tidyMacro_fSpectralFEVD(SEXP DSEXP, SEXP irf_sSEXP, SEXP bandSEXP, SEXP JSEXP, SEXP fourierSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< const arma::cube& >::type D(DSEXP);
    Rcpp::traits::input_parameter< const arma::mat& >::type irf_s(irf_sSEXP);
    Rcpp::traits::input_parameter< const arma::vec& >::type band(bandSEXP);
    Rcpp::traits::input_parameter< int >::type J(JSEXP);
    Rcpp::traits::input_parameter< bool >::type fourier(fourierSEXP);
    rcpp_result_gen = Rcpp::wrap(fSpectralFEVD(D, irf_s, band, J, fourier));
    return rcpp_result_gen;
END_RCPP
}
// fUhligIRF
arma::mat fUhligIRF(const arma::cube& wold, const arma::mat& S, int idx);
RcppExport SEXP _tidyMacro_fUhligIRF(SEXP woldSEXP, SEXP SSEXP, SEXP idxSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< const arma::cube& >::type wold(woldSEXP);
    Rcpp::traits::input_parameter< const arma::mat& >::type S(SSEXP);
    Rcpp::traits::input_parameter< int >::type idx(idxSEXP);
    rcpp_result_gen = Rcpp::wrap(fUhligIRF(wold, S, idx));
    return rcpp_result_gen;
END_RCPP
}
// fUhligMaxShare
arma::vec fUhligMaxShare(const arma::cube& wold, const arma::mat& S, int idx);
RcppExport SEXP _tidyMacro_fUhligMaxShare(SEXP woldSEXP, SEXP SSEXP, SEXP idxSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< const arma::cube& >::type wold(woldSEXP);
    Rcpp::traits::input_parameter< const arma::mat& >::type S(SSEXP);
    Rcpp::traits::input_parameter< int >::type idx(idxSEXP);
    rcpp_result_gen = Rcpp::wrap(fUhligMaxShare(wold, S, idx));
    return rcpp_result_gen;
END_RCPP
}
// fVAR
Rcpp::List fVAR(const arma::mat& y, int p, int c, Rcpp::Nullable<arma::mat> exog);
RcppExport SEXP _tidyMacro_fVAR(SEXP ySEXP, SEXP pSEXP, SEXP cSEXP, SEXP exogSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< const arma::mat& >::type y(ySEXP);
    Rcpp::traits::input_parameter< int >::type p(pSEXP);
    Rcpp::traits::input_parameter< int >::type c(cSEXP);
    Rcpp::traits::input_parameter< Rcpp::Nullable<arma::mat> >::type exog(exogSEXP);
    rcpp_result_gen = Rcpp::wrap(fVAR(y, p, c, exog));
    return rcpp_result_gen;
END_RCPP
}
// fVARX
Rcpp::List fVARX(const arma::mat& y, const arma::mat& ex, int p, int c);
RcppExport SEXP _tidyMacro_fVARX(SEXP ySEXP, SEXP exSEXP, SEXP pSEXP, SEXP cSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< const arma::mat& >::type y(ySEXP);
    Rcpp::traits::input_parameter< const arma::mat& >::type ex(exSEXP);
    Rcpp::traits::input_parameter< int >::type p(pSEXP);
    Rcpp::traits::input_parameter< int >::type c(cSEXP);
    rcpp_result_gen = Rcpp::wrap(fVARX(y, ex, p, c));
    return rcpp_result_gen;
END_RCPP
}
// fWoldIRF
arma::cube fWoldIRF(const Rcpp::List& fVAR, int horizon);
RcppExport SEXP _tidyMacro_fWoldIRF(SEXP fVARSEXP, SEXP horizonSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< const Rcpp::List& >::type fVAR(fVARSEXP);
    Rcpp::traits::input_parameter< int >::type horizon(horizonSEXP);
    rcpp_result_gen = Rcpp::wrap(fWoldIRF(fVAR, horizon));
    return rcpp_result_gen;
END_RCPP
}

static const R_CallMethodDef CallEntries[] = {
    {"_tidyMacro_fAICBIC", (DL_FUNC) &_tidyMacro_fAICBIC, 4},
    {"_tidyMacro_fBQIRF", (DL_FUNC) &_tidyMacro_fBQIRF, 3},
    {"_tidyMacro_fBootstrapBQ", (DL_FUNC) &_tidyMacro_fBootstrapBQ, 10},
    {"_tidyMacro_fBootstrapChol", (DL_FUNC) &_tidyMacro_fBootstrapChol, 9},
    {"_tidyMacro_fBootstrapCholCorrected", (DL_FUNC) &_tidyMacro_fBootstrapCholCorrected, 10},
    {"_tidyMacro_fBootstrapIVInvertible", (DL_FUNC) &_tidyMacro_fBootstrapIVInvertible, 10},
    {"_tidyMacro_fBootstrapIVMBB", (DL_FUNC) &_tidyMacro_fBootstrapIVMBB, 13},
    {"_tidyMacro_fBootstrapIVRecover", (DL_FUNC) &_tidyMacro_fBootstrapIVRecover, 13},
    {"_tidyMacro_fBootstrapMax", (DL_FUNC) &_tidyMacro_fBootstrapMax, 11},
    {"_tidyMacro_fBootstrapMaxCorrected", (DL_FUNC) &_tidyMacro_fBootstrapMaxCorrected, 12},
    {"_tidyMacro_fBootstrapUhlig", (DL_FUNC) &_tidyMacro_fBootstrapUhlig, 10},
    {"_tidyMacro_fBootstrapUhligCorrected", (DL_FUNC) &_tidyMacro_fBootstrapUhligCorrected, 11},
    {"_tidyMacro_fBootstrapVAR", (DL_FUNC) &_tidyMacro_fBootstrapVAR, 3},
    {"_tidyMacro_fCheckRestrictions", (DL_FUNC) &_tidyMacro_fCheckRestrictions, 4},
    {"_tidyMacro_fCholeskyIRF", (DL_FUNC) &_tidyMacro_fCholeskyIRF, 2},
    {"_tidyMacro_fCompanionMatrix", (DL_FUNC) &_tidyMacro_fCompanionMatrix, 3},
    {"_tidyMacro_fFEVDChol", (DL_FUNC) &_tidyMacro_fFEVDChol, 2},
    {"_tidyMacro_fFEVDIV", (DL_FUNC) &_tidyMacro_fFEVDIV, 9},
    {"_tidyMacro_fGenerateQ", (DL_FUNC) &_tidyMacro_fGenerateQ, 1},
    {"_tidyMacro_fGenerateVARData", (DL_FUNC) &_tidyMacro_fGenerateVARData, 5},
    {"_tidyMacro_fGetBands", (DL_FUNC) &_tidyMacro_fGetBands, 2},
    {"_tidyMacro_fGetShock", (DL_FUNC) &_tidyMacro_fGetShock, 5},
    {"_tidyMacro_fHDIV", (DL_FUNC) &_tidyMacro_fHDIV, 6},
    {"_tidyMacro_fBootstrapHDIV", (DL_FUNC) &_tidyMacro_fBootstrapHDIV, 11},
    {"_tidyMacro_fHeteroIRF", (DL_FUNC) &_tidyMacro_fHeteroIRF, 7},
    {"_tidyMacro_fBootstrapHetero", (DL_FUNC) &_tidyMacro_fBootstrapHetero, 13},
    {"_tidyMacro_fHistDec", (DL_FUNC) &_tidyMacro_fHistDec, 4},
    {"_tidyMacro_fLP_cpp", (DL_FUNC) &_tidyMacro_fLP_cpp, 12},
    {"_tidyMacro_fLPDID_cpp", (DL_FUNC) &_tidyMacro_fLPDID_cpp, 15},
    {"_tidyMacro_fLPIV_cpp", (DL_FUNC) &_tidyMacro_fLPIV_cpp, 11},
    {"_tidyMacro_fLPPanel_cpp", (DL_FUNC) &_tidyMacro_fLPPanel_cpp, 13},
    {"_tidyMacro_fLagMakerMatrix", (DL_FUNC) &_tidyMacro_fLagMakerMatrix, 2},
    {"_tidyMacro_fMBBVAR", (DL_FUNC) &_tidyMacro_fMBBVAR, 4},
    {"_tidyMacro_fMSW", (DL_FUNC) &_tidyMacro_fMSW, 9},
    {"_tidyMacro_fMaxIRF", (DL_FUNC) &_tidyMacro_fMaxIRF, 3},
    {"_tidyMacro_fOLS", (DL_FUNC) &_tidyMacro_fOLS, 4},
    {"_tidyMacro_fPolyConvolve", (DL_FUNC) &_tidyMacro_fPolyConvolve, 3},
    {"_tidyMacro_fRemoveBias", (DL_FUNC) &_tidyMacro_fRemoveBias, 4},
    {"_tidyMacro_fSVARSteps", (DL_FUNC) &_tidyMacro_fSVARSteps, 0},
    {"_tidyMacro_fSpectralFEVD", (DL_FUNC) &_tidyMacro_fSpectralFEVD, 5},
    {"_tidyMacro_fUhligIRF", (DL_FUNC) &_tidyMacro_fUhligIRF, 3},
    {"_tidyMacro_fUhligMaxShare", (DL_FUNC) &_tidyMacro_fUhligMaxShare, 3},
    {"_tidyMacro_fVAR", (DL_FUNC) &_tidyMacro_fVAR, 4},
    {"_tidyMacro_fVARX", (DL_FUNC) &_tidyMacro_fVARX, 4},
    {"_tidyMacro_fWoldIRF", (DL_FUNC) &_tidyMacro_fWoldIRF, 2},
    {NULL, NULL, 0}
};

RcppExport void R_init_tidyMacro(DllInfo *dll) {
    R_registerRoutines(dll, NULL, CallEntries, NULL, NULL);
    R_useDynamicSymbols(dll, FALSE);
}
