// Generated by using Rcpp::compileAttributes() -> do not edit by hand
// Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#include <RcppArmadillo.h>
#include <Rcpp.h>

using namespace Rcpp;

#ifdef RCPP_USE_GLOBAL_ROSTREAM
Rcpp::Rostream<true>&  Rcpp::Rcout = Rcpp::Rcpp_cout_get();
Rcpp::Rostream<false>& Rcpp::Rcerr = Rcpp::Rcpp_cerr_get();
#endif

// fAICBIC
Rcpp::List fAICBIC(const arma::mat& y, int pmax, int c, Rcpp::Nullable<arma::mat> exog);
RcppExport SEXP _tidyMacro_fAICBIC(SEXP ySEXP, SEXP pmaxSEXP, SEXP cSEXP, SEXP exogSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< const arma::mat& >::type y(ySEXP);
    Rcpp::traits::input_parameter< int >::type pmax(pmaxSEXP);
    Rcpp::traits::input_parameter< int >::type c(cSEXP);
    Rcpp::traits::input_parameter< Rcpp::Nullable<arma::mat> >::type exog(exogSEXP);
    rcpp_result_gen = Rcpp::wrap(fAICBIC(y, pmax, c, exog));
    return rcpp_result_gen;
END_RCPP
}
// fOLS
Rcpp::List fOLS(arma::mat y, arma::mat X, int c);
RcppExport SEXP _tidyMacro_fOLS(SEXP ySEXP, SEXP XSEXP, SEXP cSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< arma::mat >::type y(ySEXP);
    Rcpp::traits::input_parameter< arma::mat >::type X(XSEXP);
    Rcpp::traits::input_parameter< int >::type c(cSEXP);
    rcpp_result_gen = Rcpp::wrap(fOLS(y, X, c));
    return rcpp_result_gen;
END_RCPP
}
// fSVAR_steps
void fSVAR_steps();
RcppExport SEXP _tidyMacro_fSVAR_steps() {
BEGIN_RCPP
    Rcpp::RNGScope rcpp_rngScope_gen;
    fSVAR_steps();
    return R_NilValue;
END_RCPP
}
// fVAR
Rcpp::List fVAR(const arma::mat& y, int p, int c, Rcpp::Nullable<arma::mat> exog);
RcppExport SEXP _tidyMacro_fVAR(SEXP ySEXP, SEXP pSEXP, SEXP cSEXP, SEXP exogSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< const arma::mat& >::type y(ySEXP);
    Rcpp::traits::input_parameter< int >::type p(pSEXP);
    Rcpp::traits::input_parameter< int >::type c(cSEXP);
    Rcpp::traits::input_parameter< Rcpp::Nullable<arma::mat> >::type exog(exogSEXP);
    rcpp_result_gen = Rcpp::wrap(fVAR(y, p, c, exog));
    return rcpp_result_gen;
END_RCPP
}
// fVARX
Rcpp::List fVARX(const arma::mat& y, const arma::mat& ex, int p, int c);
RcppExport SEXP _tidyMacro_fVARX(SEXP ySEXP, SEXP exSEXP, SEXP pSEXP, SEXP cSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< const arma::mat& >::type y(ySEXP);
    Rcpp::traits::input_parameter< const arma::mat& >::type ex(exSEXP);
    Rcpp::traits::input_parameter< int >::type p(pSEXP);
    Rcpp::traits::input_parameter< int >::type c(cSEXP);
    rcpp_result_gen = Rcpp::wrap(fVARX(y, ex, p, c));
    return rcpp_result_gen;
END_RCPP
}
// fbootstrapChol
Rcpp::List fbootstrapChol(const arma::mat& y, const Rcpp::List& var_result, int nboot, int horizon, double prc, const std::string& bootscheme, Rcpp::Nullable<arma::mat> exog, int n_threads);
RcppExport SEXP _tidyMacro_fbootstrapChol(SEXP ySEXP, SEXP var_resultSEXP, SEXP nbootSEXP, SEXP horizonSEXP, SEXP prcSEXP, SEXP bootschemeSEXP, SEXP exogSEXP, SEXP n_threadsSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< const arma::mat& >::type y(ySEXP);
    Rcpp::traits::input_parameter< const Rcpp::List& >::type var_result(var_resultSEXP);
    Rcpp::traits::input_parameter< int >::type nboot(nbootSEXP);
    Rcpp::traits::input_parameter< int >::type horizon(horizonSEXP);
    Rcpp::traits::input_parameter< double >::type prc(prcSEXP);
    Rcpp::traits::input_parameter< const std::string& >::type bootscheme(bootschemeSEXP);
    Rcpp::traits::input_parameter< Rcpp::Nullable<arma::mat> >::type exog(exogSEXP);
    Rcpp::traits::input_parameter< int >::type n_threads(n_threadsSEXP);
    rcpp_result_gen = Rcpp::wrap(fbootstrapChol(y, var_result, nboot, horizon, prc, bootscheme, exog, n_threads));
    return rcpp_result_gen;
END_RCPP
}
// fbootstrapCholCorrected
Rcpp::List fbootstrapCholCorrected(const arma::mat& y, const Rcpp::List& var_result, int nboot1, int nboot2, int horizon, double prc, const std::string& bootscheme, Rcpp::Nullable<arma::mat> exog, int n_threads);
RcppExport SEXP _tidyMacro_fbootstrapCholCorrected(SEXP ySEXP, SEXP var_resultSEXP, SEXP nboot1SEXP, SEXP nboot2SEXP, SEXP horizonSEXP, SEXP prcSEXP, SEXP bootschemeSEXP, SEXP exogSEXP, SEXP n_threadsSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< const arma::mat& >::type y(ySEXP);
    Rcpp::traits::input_parameter< const Rcpp::List& >::type var_result(var_resultSEXP);
    Rcpp::traits::input_parameter< int >::type nboot1(nboot1SEXP);
    Rcpp::traits::input_parameter< int >::type nboot2(nboot2SEXP);
    Rcpp::traits::input_parameter< int >::type horizon(horizonSEXP);
    Rcpp::traits::input_parameter< double >::type prc(prcSEXP);
    Rcpp::traits::input_parameter< const std::string& >::type bootscheme(bootschemeSEXP);
    Rcpp::traits::input_parameter< Rcpp::Nullable<arma::mat> >::type exog(exogSEXP);
    Rcpp::traits::input_parameter< int >::type n_threads(n_threadsSEXP);
    rcpp_result_gen = Rcpp::wrap(fbootstrapCholCorrected(y, var_result, nboot1, nboot2, horizon, prc, bootscheme, exog, n_threads));
    return rcpp_result_gen;
END_RCPP
}
// fbootstrapIV_mbb
Rcpp::List fbootstrapIV_mbb(const arma::mat& y, const Rcpp::List& var_result, const arma::mat& Z, int nboot, int blocksize, const arma::ivec& adjustZ, const arma::ivec& adjustu, int policyvar, int horizon, double prc, Rcpp::Nullable<arma::mat> exog, int n_threads);
RcppExport SEXP _tidyMacro_fbootstrapIV_mbb(SEXP ySEXP, SEXP var_resultSEXP, SEXP ZSEXP, SEXP nbootSEXP, SEXP blocksizeSEXP, SEXP adjustZSEXP, SEXP adjustuSEXP, SEXP policyvarSEXP, SEXP horizonSEXP, SEXP prcSEXP, SEXP exogSEXP, SEXP n_threadsSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< const arma::mat& >::type y(ySEXP);
    Rcpp::traits::input_parameter< const Rcpp::List& >::type var_result(var_resultSEXP);
    Rcpp::traits::input_parameter< const arma::mat& >::type Z(ZSEXP);
    Rcpp::traits::input_parameter< int >::type nboot(nbootSEXP);
    Rcpp::traits::input_parameter< int >::type blocksize(blocksizeSEXP);
    Rcpp::traits::input_parameter< const arma::ivec& >::type adjustZ(adjustZSEXP);
    Rcpp::traits::input_parameter< const arma::ivec& >::type adjustu(adjustuSEXP);
    Rcpp::traits::input_parameter< int >::type policyvar(policyvarSEXP);
    Rcpp::traits::input_parameter< int >::type horizon(horizonSEXP);
    Rcpp::traits::input_parameter< double >::type prc(prcSEXP);
    Rcpp::traits::input_parameter< Rcpp::Nullable<arma::mat> >::type exog(exogSEXP);
    Rcpp::traits::input_parameter< int >::type n_threads(n_threadsSEXP);
    rcpp_result_gen = Rcpp::wrap(fbootstrapIV_mbb(y, var_result, Z, nboot, blocksize, adjustZ, adjustu, policyvar, horizon, prc, exog, n_threads));
    return rcpp_result_gen;
END_RCPP
}
// fbootstrapVAR
Rcpp::List fbootstrapVAR(const arma::mat& y, const Rcpp::List& fVAR_result, const std::string& bootscheme);
RcppExport SEXP _tidyMacro_fbootstrapVAR(SEXP ySEXP, SEXP fVAR_resultSEXP, SEXP bootschemeSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< const arma::mat& >::type y(ySEXP);
    Rcpp::traits::input_parameter< const Rcpp::List& >::type fVAR_result(fVAR_resultSEXP);
    Rcpp::traits::input_parameter< const std::string& >::type bootscheme(bootschemeSEXP);
    rcpp_result_gen = Rcpp::wrap(fbootstrapVAR(y, fVAR_result, bootscheme));
    return rcpp_result_gen;
END_RCPP
}
// fcholeskyIRF
arma::cube fcholeskyIRF(const arma::cube& wold, const arma::mat& S);
RcppExport SEXP _tidyMacro_fcholeskyIRF(SEXP woldSEXP, SEXP SSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< const arma::cube& >::type wold(woldSEXP);
    Rcpp::traits::input_parameter< const arma::mat& >::type S(SSEXP);
    rcpp_result_gen = Rcpp::wrap(fcholeskyIRF(wold, S));
    return rcpp_result_gen;
END_RCPP
}
// fcompanionMatrix
Rcpp::List fcompanionMatrix(arma::mat beta, int c, int p);
RcppExport SEXP _tidyMacro_fcompanionMatrix(SEXP betaSEXP, SEXP cSEXP, SEXP pSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< arma::mat >::type beta(betaSEXP);
    Rcpp::traits::input_parameter< int >::type c(cSEXP);
    Rcpp::traits::input_parameter< int >::type p(pSEXP);
    rcpp_result_gen = Rcpp::wrap(fcompanionMatrix(beta, c, p));
    return rcpp_result_gen;
END_RCPP
}
// fevd_chol
Rcpp::List fevd_chol(const arma::cube& chol_irf, int shock);
RcppExport SEXP _tidyMacro_fevd_chol(SEXP chol_irfSEXP, SEXP shockSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< const arma::cube& >::type chol_irf(chol_irfSEXP);
    Rcpp::traits::input_parameter< int >::type shock(shockSEXP);
    rcpp_result_gen = Rcpp::wrap(fevd_chol(chol_irf, shock));
    return rcpp_result_gen;
END_RCPP
}
// fevd_iv
Rcpp::List fevd_iv(arma::vec s, arma::mat S, arma::cube wold, int N, int hor, arma::mat sigma, arma::mat u, int T1, int p);
RcppExport SEXP _tidyMacro_fevd_iv(SEXP sSEXP, SEXP SSEXP, SEXP woldSEXP, SEXP NSEXP, SEXP horSEXP, SEXP sigmaSEXP, SEXP uSEXP, SEXP T1SEXP, SEXP pSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< arma::vec >::type s(sSEXP);
    Rcpp::traits::input_parameter< arma::mat >::type S(SSEXP);
    Rcpp::traits::input_parameter< arma::cube >::type wold(woldSEXP);
    Rcpp::traits::input_parameter< int >::type N(NSEXP);
    Rcpp::traits::input_parameter< int >::type hor(horSEXP);
    Rcpp::traits::input_parameter< arma::mat >::type sigma(sigmaSEXP);
    Rcpp::traits::input_parameter< arma::mat >::type u(uSEXP);
    Rcpp::traits::input_parameter< int >::type T1(T1SEXP);
    Rcpp::traits::input_parameter< int >::type p(pSEXP);
    rcpp_result_gen = Rcpp::wrap(fevd_iv(s, S, wold, N, hor, sigma, u, T1, p));
    return rcpp_result_gen;
END_RCPP
}
// fgenerateVARdata
arma::mat fgenerateVARdata(const arma::mat& y, int p, int c, const arma::mat& beta, const arma::mat& residuals);
RcppExport SEXP _tidyMacro_fgenerateVARdata(SEXP ySEXP, SEXP pSEXP, SEXP cSEXP, SEXP betaSEXP, SEXP residualsSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< const arma::mat& >::type y(ySEXP);
    Rcpp::traits::input_parameter< int >::type p(pSEXP);
    Rcpp::traits::input_parameter< int >::type c(cSEXP);
    Rcpp::traits::input_parameter< const arma::mat& >::type beta(betaSEXP);
    Rcpp::traits::input_parameter< const arma::mat& >::type residuals(residualsSEXP);
    rcpp_result_gen = Rcpp::wrap(fgenerateVARdata(y, p, c, beta, residuals));
    return rcpp_result_gen;
END_RCPP
}
// fhistdec
Rcpp::List fhistdec(const arma::mat& y, const Rcpp::List& fVAR, const arma::mat& K, int series);
RcppExport SEXP _tidyMacro_fhistdec(SEXP ySEXP, SEXP fVARSEXP, SEXP KSEXP, SEXP seriesSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< const arma::mat& >::type y(ySEXP);
    Rcpp::traits::input_parameter< const Rcpp::List& >::type fVAR(fVARSEXP);
    Rcpp::traits::input_parameter< const arma::mat& >::type K(KSEXP);
    Rcpp::traits::input_parameter< int >::type series(seriesSEXP);
    rcpp_result_gen = Rcpp::wrap(fhistdec(y, fVAR, K, series));
    return rcpp_result_gen;
END_RCPP
}
// flagmakerMatrix
arma::mat flagmakerMatrix(arma::mat y, int p);
RcppExport SEXP _tidyMacro_flagmakerMatrix(SEXP ySEXP, SEXP pSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< arma::mat >::type y(ySEXP);
    Rcpp::traits::input_parameter< int >::type p(pSEXP);
    rcpp_result_gen = Rcpp::wrap(flagmakerMatrix(y, p));
    return rcpp_result_gen;
END_RCPP
}
// fmbb_var
Rcpp::List fmbb_var(const arma::mat& eps, int lags, int BlockSize, Rcpp::Nullable<arma::mat> M);
RcppExport SEXP _tidyMacro_fmbb_var(SEXP epsSEXP, SEXP lagsSEXP, SEXP BlockSizeSEXP, SEXP MSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< const arma::mat& >::type eps(epsSEXP);
    Rcpp::traits::input_parameter< int >::type lags(lagsSEXP);
    Rcpp::traits::input_parameter< int >::type BlockSize(BlockSizeSEXP);
    Rcpp::traits::input_parameter< Rcpp::Nullable<arma::mat> >::type M(MSEXP);
    rcpp_result_gen = Rcpp::wrap(fmbb_var(eps, lags, BlockSize, M));
    return rcpp_result_gen;
END_RCPP
}
// fremove_bias
Rcpp::List fremove_bias(const arma::mat& beta, int c, int p, const arma::cube& boot_beta);
RcppExport SEXP _tidyMacro_fremove_bias(SEXP betaSEXP, SEXP cSEXP, SEXP pSEXP, SEXP boot_betaSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< const arma::mat& >::type beta(betaSEXP);
    Rcpp::traits::input_parameter< int >::type c(cSEXP);
    Rcpp::traits::input_parameter< int >::type p(pSEXP);
    Rcpp::traits::input_parameter< const arma::cube& >::type boot_beta(boot_betaSEXP);
    rcpp_result_gen = Rcpp::wrap(fremove_bias(beta, c, p, boot_beta));
    return rcpp_result_gen;
END_RCPP
}
// fwoldIRF
arma::cube fwoldIRF(const Rcpp::List& fVAR, int horizon);
RcppExport SEXP _tidyMacro_fwoldIRF(SEXP fVARSEXP, SEXP horizonSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< const Rcpp::List& >::type fVAR(fVARSEXP);
    Rcpp::traits::input_parameter< int >::type horizon(horizonSEXP);
    rcpp_result_gen = Rcpp::wrap(fwoldIRF(fVAR, horizon));
    return rcpp_result_gen;
END_RCPP
}

static const R_CallMethodDef CallEntries[] = {
    {"_tidyMacro_fAICBIC", (DL_FUNC) &_tidyMacro_fAICBIC, 4},
    {"_tidyMacro_fOLS", (DL_FUNC) &_tidyMacro_fOLS, 3},
    {"_tidyMacro_fSVAR_steps", (DL_FUNC) &_tidyMacro_fSVAR_steps, 0},
    {"_tidyMacro_fVAR", (DL_FUNC) &_tidyMacro_fVAR, 4},
    {"_tidyMacro_fVARX", (DL_FUNC) &_tidyMacro_fVARX, 4},
    {"_tidyMacro_fbootstrapChol", (DL_FUNC) &_tidyMacro_fbootstrapChol, 8},
    {"_tidyMacro_fbootstrapCholCorrected", (DL_FUNC) &_tidyMacro_fbootstrapCholCorrected, 9},
    {"_tidyMacro_fbootstrapIV_mbb", (DL_FUNC) &_tidyMacro_fbootstrapIV_mbb, 12},
    {"_tidyMacro_fbootstrapVAR", (DL_FUNC) &_tidyMacro_fbootstrapVAR, 3},
    {"_tidyMacro_fcholeskyIRF", (DL_FUNC) &_tidyMacro_fcholeskyIRF, 2},
    {"_tidyMacro_fcompanionMatrix", (DL_FUNC) &_tidyMacro_fcompanionMatrix, 3},
    {"_tidyMacro_fevd_chol", (DL_FUNC) &_tidyMacro_fevd_chol, 2},
    {"_tidyMacro_fevd_iv", (DL_FUNC) &_tidyMacro_fevd_iv, 9},
    {"_tidyMacro_fgenerateVARdata", (DL_FUNC) &_tidyMacro_fgenerateVARdata, 5},
    {"_tidyMacro_fhistdec", (DL_FUNC) &_tidyMacro_fhistdec, 4},
    {"_tidyMacro_flagmakerMatrix", (DL_FUNC) &_tidyMacro_flagmakerMatrix, 2},
    {"_tidyMacro_fmbb_var", (DL_FUNC) &_tidyMacro_fmbb_var, 4},
    {"_tidyMacro_fremove_bias", (DL_FUNC) &_tidyMacro_fremove_bias, 4},
    {"_tidyMacro_fwoldIRF", (DL_FUNC) &_tidyMacro_fwoldIRF, 2},
    {NULL, NULL, 0}
};

RcppExport void R_init_tidyMacro(DllInfo *dll) {
    R_registerRoutines(dll, NULL, CallEntries, NULL, NULL);
    R_useDynamicSymbols(dll, FALSE);
}
