# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#' Determine Optimal Lag Order for VAR Model Using Information Criteria
#'
#' Fits VAR models for lag orders 1 through \code{pmax} and returns the lag
#' length that minimises each of three information criteria.
#'
#' @param y A T x N matrix of endogenous variables (T observations, N series).
#' @param pmax An integer specifying the maximum VAR lag order to consider.
#' @param c An integer (0 or 1) indicating whether to include a constant term
#'   (1 = include, 0 = exclude).
#' @param exog An optional T x M matrix of exogenous variables. Default is
#'   NULL.
#'
#' @return A list with three integer elements: aic — optimal lag length by
#'   Akaike IC; bic — optimal lag length by Bayesian IC; hq — optimal lag
#'   length by Hannan-Quinn IC.
#'
#' @details
#' For each candidate lag order p the residual covariance Sigma = (e'e)/T is
#' computed and the three criteria are evaluated as:
#'
#' AIC = log(det(Sigma)) + 2 * (p*N^2 + N + M) / T
#'
#' BIC = log(det(Sigma)) + log(T) * (p*N^2 + N + M) / T
#'
#' HQ  = log(det(Sigma)) + 2 * log(log(T)) * (p*N^2 + N + M) / T
#'
#' where M is the number of exogenous variables.
#'
#' @examples
#' \dontrun{
#' set.seed(123)
#' y      <- matrix(rnorm(200), ncol = 2)
#' result <- fAICBIC(y, pmax = 10, c = 1)
#' result$aic
#' result$bic
#' }
#'
#' @seealso \code{\link{fVAR}}
#'
#' @export
fAICBIC <- function(y, pmax, c, exog = NULL) {
    .Call(`_tidyMacro_fAICBIC`, y, pmax, c, exog)
}

#' Ordinary Least Squares Regression
#'
#' @param y Dependent variable matrix! not vector
#' @param X Independent variables matrix (T x N)
#' @param c Integer indicator for intercept (1 if intercept included, 0 otherwise)
#'
#' @return A list containing:
#'   \itemize{
#'     \item beta: Coefficient estimates ((N+1) x 1 if c=1, N x 1 if c=0)
#'     \item fitted: Fitted values (T x 1)
#'     \item err: Residuals (T x 1)
#'     \item r2: R-squared statistic (scalar)
#'     \item fitted_partial: Fitted values excluding intercept (T x 1)
#'   }
#'
#' @details
#' This function performs ordinary least squares (OLS) regression. The coefficient
#' estimates are computed using the normal equations:
#' \deqn{\hat{\beta} = (X'X)^{-1}X'y}
#'
#' The R-squared statistic measures the proportion of variance explained:
#' \deqn{R^2 = 1 - \frac{RSS}{TSS}}
#' where RSS is the residual sum of squares and TSS is the total sum of squares.
#'
#' If an intercept is included (c=1), fitted_partial contains the fitted values
#' excluding the intercept contribution, useful for assessing the explanatory
#' power of the regressors alone.
#'
#' @examples
#' \dontrun{
#' # Generate sample data
#' set.seed(123)
#' y <- rnorm(100)
#' X <- matrix(rnorm(200), 100, 2)
#' 
#' # OLS with intercept
#' result <- fOLS(y, X, c = 1)
#' print(result$beta)
#' print(result$r2)
#' 
#' # OLS without intercept
#' result_no_int <- fOLS(y, X, c = 0)
#' }
#'
#' @export
fOLS <- function(y, X, c = 1L) {
    .Call(`_tidyMacro_fOLS`, y, X, c)
}

#' Print SVAR Identification Steps
#'
#' Prints a numbered guide to the proxy-SVAR identification and
#' invertibility-testing procedure to the R console.
#'
#' @return Called for its side-effect of printing to the console.
#'   Returns \code{NULL} invisibly.
#'
#' @details
#' Step 1: Estimate the VAR(p) and extract the residuals.
#'
#' Step 2: Regress the instrument on the current residuals plus f leads;
#' save the fitted value.
#'
#' Step 3: F-test whether the lead coefficients are jointly zero. Rejection
#' implies the shock is non-invertible.
#'
#' Step 4: If invertible, apply the standard Stock-Watson IV procedure to
#' obtain IRFs and unit-variance shocks.
#'
#' Step 5: If non-invertible, test recoverability via the Ljung-Box test on
#' the fitted instrument series.
#'
#' Step 6: If recoverable (null of no autocorrelation not rejected), repeat
#' the IV procedure adding residual leads to the first-stage regression.
#'
#' Step 7: If recoverability is rejected, SVAR analysis with this instrument
#' is not feasible.
#'
#' @examples
#' fSVAR_steps()
#'
#' @export
fSVAR_steps <- function() {
    invisible(.Call(`_tidyMacro_fSVAR_steps`))
}

#' Vector Autoregression (VAR) Model Estimation
#'
#' Estimates a Vector Autoregression model with optional exogenous variables
#' using ordinary least squares (OLS). Optimised for maximum speed and memory
#' efficiency via RcppArmadillo.
#'
#' @param y A numeric matrix of time series data with T rows (time periods)
#'   and N columns (endogenous variables).
#' @param p An integer specifying the number of lags to include in the VAR.
#' @param c An integer indicator for including a constant term (1 = include
#'   intercept, 0 = no intercept).
#' @param exog An optional T x M matrix of exogenous variables. If provided,
#'   these variables enter contemporaneously (not lagged). Default is NULL.
#'
#' @return A list with elements: beta — coefficient matrix of dimensions
#'   (Np + c + M) x N, where the first row is the intercept (if c = 1),
#'   followed by N*p lag-coefficient rows, then M exogenous-coefficient rows;
#'   residuals — (T-p) x N matrix of OLS residuals;
#'   sigma_full — N x N residual covariance matrix normalised by (n_obs - 1);
#'   p — lag order (echoed from input);
#'   c — intercept indicator (echoed from input);
#'   n_exog — number of exogenous variables (0 if none provided).
#'
#' @details
#' The model is \deqn{Y_t = c + A_1 Y_{t-1} + \cdots + A_p Y_{t-p} + B X_t + e_t}
#' where \eqn{X_t} are contemporaneous exogenous variables. Without exogenous
#' variables the model reduces to a standard VAR(p). Estimation uses
#' \code{arma::solve} for numerical stability.
#'
#' @examples
#' \dontrun{
#' # VAR(2) without exogenous variables
#' y      <- matrix(rnorm(200), ncol = 2)
#' result <- fVAR(y, p = 2, c = 1)
#'
#' # VAR(2) with one exogenous variable
#' exog   <- matrix(rnorm(100), ncol = 1)
#' result <- fVAR(y, p = 2, c = 1, exog = exog)
#' }
#'
#' @seealso \code{\link{fwoldIRF}}, \code{\link{fbootstrapChol}},
#'   \code{\link{fAICBIC}}
#'
#' @export
fVAR <- function(y, p, c, exog = NULL) {
    .Call(`_tidyMacro_fVAR`, y, p, c, exog)
}

#' Vector Autoregression with Exogenous Variables (VARX) Model Estimation
#'
#' Estimates a VARX(p) model where both endogenous and exogenous variables
#' are lagged using ordinary least squares (OLS). Optimised for maximum
#' speed and memory efficiency.
#'
#' @param y A numeric matrix of endogenous time series data with T rows
#'   (time periods) and N columns (variables).
#' @param ex A numeric matrix of exogenous time series data with T rows
#'   (time periods) and M columns (variables).
#' @param p An integer specifying the number of lags for both endogenous
#'   and exogenous variables.
#' @param c An integer indicator for including a constant term (1 = include
#'   intercept, 0 = no intercept).
#'
#' @return A list with two elements: beta — coefficient matrix of dimensions
#'   (Np + M + Mp + c) x N; residuals — (T-p) x N residual matrix.
#'
#' @details
#' The VARX(p) model is:
#' \deqn{Y_t = c + A_1 Y_{t-1} + \cdots + A_p Y_{t-p}
#'            + B_0 X_t + B_1 X_{t-1} + \cdots + B_p X_{t-p} + e_t}
#' Both endogenous and exogenous variables are lagged p periods.
#' Exogenous variables also enter contemporaneously at time t.
#'
#' @examples
#' \dontrun{
#' y  <- matrix(rnorm(200), ncol = 2)
#' ex <- matrix(rnorm(100), ncol = 1)
#' result    <- fVARX(y, ex, p = 2, c = 1)
#' beta      <- result$beta
#' residuals <- result$residuals
#' }
#'
#' @export
fVARX <- function(y, ex, p, c) {
    .Call(`_tidyMacro_fVARX`, y, ex, p, c)
}

#' Bootstrap Cholesky Impulse Response Functions
#'
#' @param y T x N matrix of original endogenous variables.
#' @param var_result List from \code{fVAR}.
#' @param nboot Number of bootstrap replications.
#' @param horizon Maximum IRF horizon.
#' @param prc Confidence level in percent (e.g. 68).
#' @param bootscheme \code{"residual"} or \code{"wild"}.
#' @param exog Optional T x M exogenous matrix. Default NULL.
#' @param n_threads OpenMP threads. 0 = all cores minus one.
#'
#' @return List: \code{bootchol}, \code{upper}, \code{lower}, \code{boot_beta}.
#'
#' @export
fbootstrapChol <- function(y, var_result, nboot, horizon, prc, bootscheme, exog = NULL, n_threads = 0L) {
    .Call(`_tidyMacro_fbootstrapChol`, y, var_result, nboot, horizon, prc, bootscheme, exog, n_threads)
}

#' Bias-Corrected Bootstrap Cholesky IRF Confidence Bands (Kilian 1998)
#'
#' @param y T x N matrix of endogenous variables.
#' @param var_result List returned by \code{fVAR()}.
#' @param nboot1 First-pass bootstrap replications for bias estimation.
#' @param nboot2 Second-pass bootstrap replications for confidence bands.
#' @param horizon Maximum IRF horizon.
#' @param prc Confidence level in percent (e.g. 68 or 90).
#' @param bootscheme \code{"residual"} or \code{"wild"}.
#' @param exog Optional T x M matrix of exogenous variables. Default NULL.
#' @param n_threads OpenMP threads. 0 = all cores minus one.
#'
#' @return List: \code{bootchol}, \code{upper}, \code{lower},
#'   \code{boot_beta}, \code{Beta}, \code{corrections}.
#'
#' @export
fbootstrapCholCorrected <- function(y, var_result, nboot1, nboot2, horizon, prc, bootscheme, exog = NULL, n_threads = 0L) {
    .Call(`_tidyMacro_fbootstrapCholCorrected`, y, var_result, nboot1, nboot2, horizon, prc, bootscheme, exog, n_threads)
}

#' Bootstrap IV Impulse Response Functions using Moving Block Bootstrap
#'
#' Computes bootstrap confidence bands for instrumental variable identified
#' impulse response functions using the moving block bootstrap to preserve
#' temporal dependence in residuals and instruments.
#'
#' @param y T x N matrix of endogenous variables
#' @param var_result List output from fVAR containing beta, residuals, p, c
#' @param Z (T-p) x K matrix of instrumental variables
#' @param nboot Integer number of bootstrap replications
#' @param blocksize Integer block size for moving block bootstrap
#' @param adjustZ Integer vector of length 2: [start, end] indices for Z
NULL

#' @param n_threads Integer number of threads for parallel computation.
#'   Default is 0 (uses all available cores). Set to 1 for single-threaded
NULL

#'
#' @return A list containing:
#'   \itemize{
#'     \item upper: N x (horizon+1) matrix of upper confidence bands
#'     \item lower: N x (horizon+1) matrix of lower confidence bands
#'     \item meanirf: N x (horizon+1) matrix of mean impulse responses
#'     \item medianirf: N x (horizon+1) matrix of median impulse responses
#'   }
#'
#' @details
#' This function implements the moving block bootstrap for IV-identified SVARs.
#' The first stage regresses the policy variable residual on the instrument(s),
#' and the second stage recovers the structural impact matrix. The
NULL

#'
#' The function uses OpenMP for parallel computation when available,
NULL

#'
#' @examples
#' \dontrun{
#' var_result <- fVAR(y, p = 2, c = 1)
#' result <- fbootstrapIV_mbb(y, var_result, Z,
#'                             nboot = 1000, blocksize = 10,
#'                             adjustZ = c(1, 100), adjustu = c(1, 100),
#'                             policyvar = 1, horizon = 20, prc = 68)
#'
#' # Use 4 threads for parallel computation
#' result <- fbootstrapIV_mbb(y, var_result, Z,
#'                             nboot = 1000, blocksize = 10,
#'                             adjustZ = c(1, 100), adjustu = c(1, 100),
#'                             policyvar = 1, horizon = 20, prc = 68,
#'                             n_threads = 4)
#' }
#'
#' @export
fbootstrapIV_mbb <- function(y, var_result, Z, nboot, blocksize, adjustZ, adjustu, policyvar, horizon, prc, exog = NULL, n_threads = 0L) {
    .Call(`_tidyMacro_fbootstrapIV_mbb`, y, var_result, Z, nboot, blocksize, adjustZ, adjustu, policyvar, horizon, prc, exog, n_threads)
}

#' Bootstrap VAR Model
#'
#' Generates a bootstrap pseudo-sample from a fitted VAR model using either
#' residual (iid) resampling or a wild (Rademacher) bootstrap scheme.
#'
#' @param y T x N matrix of original endogenous variables.
#' @param fVAR_result List from \code{fVAR} containing beta, residuals, p,
#'   and c.
#' @param bootscheme String indicating the bootstrap method: "residual" for
#'   iid resampling of residuals, or "wild" for a Rademacher wild bootstrap.
#'
#' @return A list with two elements: ynext — T x N bootstrapped data matrix
#'   (first p rows copied from \code{y}); rademacher — T_eff-length vector of
#'   Rademacher signs used in the wild scheme (all zeros for residual scheme).
#'
#' @details
#' The recursion is \deqn{y_t = c + A_1 y_{t-1} + \cdots + A_p y_{t-p} + e_t^*}
#' where \eqn{e_t^*} is either a randomly resampled residual (residual scheme)
#' or the t-th residual multiplied by a Rademacher sign (wild scheme).
#'
#' @seealso \code{\link{fbootstrapChol}}, \code{\link{fVAR}}
#'
#' @export
fbootstrapVAR <- function(y, fVAR_result, bootscheme = "residual") {
    .Call(`_tidyMacro_fbootstrapVAR`, y, fVAR_result, bootscheme)
}

#' Compute Cholesky Impulse Response Functions
#'
#' @param wold Wold representation cube (N x N x horizon)
#' @param S Cholesky factor matrix (N x N), lower triangular
#'
#' @return A cube containing:
#'   Cholesky structural impulse response functions (N x N x horizon)
#'
#' @details
#' This function computes structural impulse response functions using the
#' Cholesky decomposition identification scheme. For each horizon h, the
#' structural IRF is computed as:
#' \deqn{IRF_h = \Psi_h \cdot S}
#' where \eqn{\Psi_h} is the Wold representation at horizon h and S is the
#' Cholesky factor (lower triangular) of the covariance matrix of reduced-form
#' residuals.
#'
#' The Cholesky identification imposes a recursive structure on the
#' contemporaneous relationships between variables, with the ordering
#' of variables determining the causal structure.
#'
#' @examples
#' \dontrun{
#' # Generate sample Wold representation
#' N <- 3
#' horizon <- 20
#' wold <- array(rnorm(N * N * horizon), dim = c(N, N, horizon))
#'
#' # Compute Cholesky factor
#' Sigma <- matrix(c(1, 0.5, 0.3,
#'                   0.5, 1, 0.4,
#'                   0.3, 0.4, 1), 3, 3)
#' S <- t(chol(Sigma))  # Lower triangular
#'
#' # Compute Cholesky IRF
#' chol_irf <- fcholeskyIRF(wold, S)
#' }
#'
#' @export
fcholeskyIRF <- function(wold, S) {
    .Call(`_tidyMacro_fcholeskyIRF`, wold, S)
}

#' Compute VAR Companion Matrix
#'
#' @param beta Coefficient matrix. Dimensions: (Np+c+M) x N,
#'   where N is the number of variables, p is the lag order,
#'   c is 1 if intercept included (0 otherwise), and M is the number of
#'   exogenous variables
#' @param c Integer indicator for intercept (1 if intercept included, 0 otherwise)
#' @param p Integer lag order of the VAR model
#'
#' @return A list containing:
#'   \itemize{
#'     \item comp: Companion matrix (Np x Np)
#'     \item N: Number of variables in the VAR system
#'   }
#'
#' @details
#' This function constructs the companion form matrix of a VAR(p) model.
#' The companion matrix representation allows the VAR(p) to be written as a
#' VAR(1) system, which is useful for various computations including impulse
#' response functions and forecasting.
#'
#' When exogenous variables are present, they are excluded from the companion
#' matrix as they do not have a dynamic feedback structure in the VAR system.
#'
#' The companion matrix has the structure:
#' \deqn{
#'   \begin{bmatrix}
#'   A_1 & A_2 & \cdots & A_{p-1} & A_p \\
#'   I_N & 0 & \cdots & 0 & 0 \\
#'   0 & I_N & \cdots & 0 & 0 \\
#'   \vdots & \vdots & \ddots & \vdots & \vdots \\
#'   0 & 0 & \cdots & I_N & 0
#'   \end{bmatrix}
#' }
#'
#' @examples
#' \dontrun{
#' # VAR(2) model with 3 variables, no intercept
#' beta <- matrix(rnorm(18), 6, 3)  # 6 rows (2*3), 3 columns
#' result <- fcompanionMatrix(beta, c = 0, p = 2)
#'
#' # VAR(2) model with 3 variables, with intercept and 2 exogenous variables
#' beta_int <- matrix(rnorm(27), 9, 3)  # 9 rows (2*3+1+2), 3 columns
#' result <- fcompanionMatrix(beta_int, c = 1, p = 2)
#' }
#'
#' @export
fcompanionMatrix <- function(beta, c, p) {
    .Call(`_tidyMacro_fcompanionMatrix`, beta, c, p)
}

#' Forecast Error Variance Decomposition for Cholesky-Identified VARs
#'
#' Computes the forecast error variance decomposition (FEVD) showing the
#' proportion of forecast error variance of each variable attributable to
#' each structural shock identified via Cholesky decomposition.
#'
#' @param chol_irf N x N x (horizon+1) cube of Cholesky impulse response functions
#'   from \code{fcholeskyIRF}. Each slice chol_irf[,,h] contains the responses at
#'   horizon h. The horizon is automatically inferred from the cube dimensions.
#' @param shock Integer (1-indexed). If provided, returns only the N x horizon
#'   matrix for that specific shock (matching MATLAB \code{variance_decomp(irf, shock)}).
#'   If 0 (default), returns the full N x N x horizon cube for all shocks.
#'
#' @return A list containing:
#'   \item{fevd}{If \code{shock = 0}: N x N x horizon cube where \code{fevd[i,j,h]}
#'     is the share of forecast error variance of variable i at horizon h explained
#'     by shock j. If \code{shock > 0}: N x horizon matrix for the specified shock.}
#'
#' @details
#' The forecast error variance decomposition measures the proportion of the
#' h-step ahead forecast error variance of variable i that is attributable to
#' each structural shock j. For Cholesky-identified VARs:
#'
#' \deqn{FEVD(i,j,h) = \frac{\sum_{s=0}^{h} [\Psi_s P]_{ij}^2}{\sum_{k=1}^{N} \sum_{s=0}^{h} [\Psi_s P]_{ik}^2}}
#'
#' @examples
#' \dontrun{
#' # Estimate VAR
#' var_result <- fVAR(y, p = 2, c = 1)
#' wold <- fwoldIRF(var_result, horizon = 20)
#' S <- t(chol(var_result$sigma_full))
#' chol_irf <- fcholeskyIRF(wold, S)
#'
#' # Full decomposition (all shocks) — returns 3D cube
#' vardec <- fevd_chol(chol_irf)
#'
#' # Single shock decomposition — returns N x horizon matrix
#' shock <- match("UNCERT", colnames(y))
#' vardec <- fevd_chol(chol_irf, shock = shock)
#' }
#'
#' @seealso \code{\link{fcholeskyIRF}}, \code{\link{fwoldIRF}},
#'   \code{\link{fplot_vardec}}, \code{\link{fevd_iv}}
#'
#' @export
fevd_chol <- function(chol_irf, shock = 0L) {
    .Call(`_tidyMacro_fevd_chol`, chol_irf, shock)
}

#' Forecast Error Variance Decomposition for IV-Identified Shocks
#'
#' Computes the forecast error variance decomposition (FEVD) for instrumental
#' variable identified structural shocks. The function scales shocks to unit
#' variance and calculates the contribution of a specific shock to the forecast
#' error variance of each variable over time.
#'
#' @param s N x 1 vector of structural impact coefficients
#' @param S N x N lower triangular Cholesky factor of the residual covariance matrix
#' @param wold N x N x (hor+1) cube of Wold impulse response functions
#' @param N Integer number of variables in the VAR system
#' @param hor Integer maximum forecast horizon
#' @param sigma N x N residual covariance matrix
#' @param u (T-p) x N matrix of VAR residuals
#' @param T1 Integer effective sample size (T-p)
#' @param p Integer lag order of the VAR model
#'
#' @return A list containing:
#'   - scaler: N x 1 vector of scaling factors for unit variance normalization
#'   - ivirf_scaled: N x (hor+1) matrix of unit variance impulse responses
#'   - oil_news_unit_var: 1 x T1 vector of unit variance shock series
#'   - check_uv: Scalar variance check (should be close to 1)
#'   - denom: N x (hor+1) matrix of total forecast error variances
#'   - fevd_iv: N x (hor+1) matrix of FEVD shares (between 0 and 1)
#'
#' @details
#' The FEVD measures the proportion of the h-step ahead forecast error variance
#' of each variable that is attributable to the identified structural shock.
#'
#' The function performs the following steps:
#' 1. Normalizes the structural shock to have unit variance
#' 2. Computes unit variance impulse responses
#' 3. Recovers the unit variance shock series
#' 4. Computes total forecast error variance at each horizon
#' 5. Computes variance due to identified shock
#' 6. Calculates FEVD as the ratio
#'
#' The FEVD values are proportions between 0 and 1, where higher values indicate
#' that the identified shock explains a larger share of the forecast error variance.
#'
#' @examples
#' \dontrun{
#' # Estimate VAR and compute Wold IRF
#' var_result <- fVAR(y, p = 2, c = 1)
#' wold <- fwoldIRF(var_result, horizon = 20)
#' 
#' # IV identification
#' s <- c(1, 0.5, 0.3)
#' sigma <- var_result$sigma_full
#' S <- t(chol(sigma))
#' 
#' # Compute FEVD
#' result <- fevd_iv(s, S, wold, N = 3, hor = 20,
#'                   sigma = sigma, u = var_result$residuals,
#'                   T1 = nrow(var_result$residuals), p = 2)
#' 
#' # Plot FEVD for first variable
#' plot(result$fevd_iv[1, ], type = "l", ylim = c(0, 1),
#'      main = "FEVD: Share of Variance Explained by Shock",
#'      xlab = "Horizon", ylab = "Share")
#' }
#'
#' @seealso \code{\link{fwoldIRF}} for computing Wold impulse responses,
#'   \code{\link{fVAR}} for VAR estimation
#'
#' @export
fevd_iv <- function(s, S, wold, N, hor, sigma, u, T1, p) {
    .Call(`_tidyMacro_fevd_iv`, s, S, wold, N, hor, sigma, u, T1, p)
}

#' Generate VAR Data
#'
#' Recursively generates VAR data from initial values, coefficients, and
#' residuals. Optimised for maximum performance and memory efficiency.
#'
#' @param y T x N matrix of initial/historical endogenous variables.
#' @param p Integer lag order of the VAR model.
#' @param c Integer indicator for intercept (1 if included, 0 otherwise).
#' @param beta Coefficient matrix: (Np+c) x N if c = 1, or Np x N if c = 0.
#' @param residuals (T-p) x N matrix of residuals/shocks to add.
#'
#' @return T x N matrix of generated VAR data. The first p rows are copied
#'   from \code{y}; the remaining T-p rows are generated recursively.
#'
#' @details
#' The recursion follows:
#' \deqn{y_t = c + A_1 y_{t-1} + \cdots + A_p y_{t-p} + e_t}
#'
#' @examples
#' \dontrun{
#' y_init    <- matrix(rnorm(200), ncol = 2)
#' beta      <- matrix(rnorm(10), 5, 2)
#' residuals <- matrix(rnorm(190), 95, 2)
#' y_new     <- fgenerateVARdata(y_init, p = 2, c = 1, beta, residuals)
#' }
#'
#' @export
fgenerateVARdata <- function(y, p, c, beta, residuals) {
    .Call(`_tidyMacro_fgenerateVARdata`, y, p, c, beta, residuals)
}

#' Historical Decomposition of a VAR Variable
#'
#' Decomposes a chosen variable's realisation into contributions from each
#' structural shock, identified via a lower-triangular Cholesky factor K.
#' Mirrors the MATLAB \code{hist_decmp(y, beta, residuals, c, p, K, series)}.
#'
#' @param y TxN numeric matrix of original (undemeaned) data.
#' @param fVAR List returned by \code{fVAR()}, containing at minimum
#'   \code{beta}, \code{residuals}, \code{sigma_full}, \code{p}, \code{c},
#'   and \code{n_exog}.
#' @param K NxN lower-triangular Cholesky factor of the residual covariance
#'   matrix (i.e. \code{t(chol(sigma_full))}).
#' @param series Integer (1-indexed) selecting which variable to decompose.
#'
#' @return A list with two elements:
#'   \item{histdec}{(T-p) x N numeric matrix. Column \code{j} is the
#'     cumulative contribution of structural shock \code{j} to the chosen
#'     variable at each point in time.}
#'   \item{ystar}{(T-p) numeric vector of the demeaned realisation of the
#'     chosen variable (benchmark series for the plot).}
#'
#' @details
#' The structural shocks are recovered as
#' \deqn{\varepsilon_t = K^{-1} u_t}
#' where \eqn{u_t} are the reduced-form residuals. The structural MA
#' representation is built by multiplying each Wold matrix by K:
#' \deqn{\Theta_h = \Psi_h K}
#' The contribution of shock \eqn{j} to variable \eqn{i} at time \eqn{t} is
#' then the inner product of \eqn{\Theta_{0:t}[i,j]} with the time-reversed
#' structural shocks \eqn{\varepsilon_{t:-1:0,j}}:
#' \deqn{HD(t,j) = \sum_{h=0}^{t} \Theta_h[i,j]\, \varepsilon_{t-h,j}}
#'
#' @examples
#' \dontrun{
#' var_result <- fVAR(y, p = 12, c = 1)
#' K <- t(chol(var_result$sigma_full))
#' series <- match("UNCERT", colnames(y))
#'
#' hd <- fhistdec(y, var_result, K, series)
#'
#' # hd$histdec is (T-p) x N; hd$ystar is the demeaned series
#' matplot(hd$histdec, type = "l")
#' lines(hd$ystar, lwd = 2)
#' }
#'
#' @seealso \code{\link{fVAR}}, \code{\link{fcholeskyIRF}},
#'   \code{\link{fwoldIRF}}, \code{\link{plothistdec}}
#'
#' @export
fhistdec <- function(y, fVAR, K, series) {
    .Call(`_tidyMacro_fhistdec`, y, fVAR, K, series)
}

#' Create Lagged Matrix
#'
#' Creates a matrix of lagged values from a time series matrix. For each
#' variable and each lag from 1 to p, this function creates a column containing
#' the lagged values, removing the first p rows to align the lags properly.
#'
#' @param y A numeric matrix, data frame, or tibble of time series data with T
#'   rows (time periods) and N columns (variables)
#' @param p An integer specifying the number of lags to create
#'
#' @return A numeric matrix with (T-p) rows and (N*p) columns. The columns are
#'   organized as: all N variables at lag 1, then all N variables at lag 2, etc.
#'   Column names are generated as "var_name_lag_k" where applicable.
#'
#' @details The function creates a lagged matrix where each column represents a
#'   lagged version of the original variables. The lags are organized by lag
#'   order first, then by variable. For example, with 2 variables and 2 lags,
#'   the column order would be: var1_lag1, var2_lag1, var1_lag2, var2_lag2.
#'
#' @examples
#' \dontrun{
#' # Create sample data as data frame
#' y <- data.frame(var1 = 1:10, var2 = 11:20)
#'
#' # Create 2 lags
#' x <- lagmakerMatrix(y, 2)
#'
#' # Works with tibbles too
#' library(tibble)
#' y_tbl <- tibble(var1 = 1:10, var2 = 11:20)
#' x <- lagmakerMatrix(y_tbl, 2)
#' }
#'
#' @export
flagmakerMatrix <- function(y, p) {
    .Call(`_tidyMacro_flagmakerMatrix`, y, p)
}

#' Moving Block Bootstrap for VAR Residuals and Instruments
#' 
#' Computes a moving-block bootstrap sample for the reduced form errors
#' of a VAR(p) model. Optionally bootstraps a matrix of instruments M.
#' 
#' @param eps (T-p) x N matrix of VAR residuals
#' @param lags Integer lag order p of the VAR model
#' @param BlockSize Integer block size for moving block bootstrap. 
#'   If 0 or negative, automatically computed as round(5.03 * T^0.25)
#' @param M Optional (T-p) x K matrix of instruments to bootstrap (default = NULL)
#' 
#' @return A list containing:
#'   \itemize{
#'     \item eps_boot: (T-p) x N matrix of bootstrapped residuals (centered)
#'     \item M_boot: (T-p) x K matrix of bootstrapped instruments (centered), 
#'                   or empty matrix if M not provided
#'   }
#' 
#' @details
#' The moving block bootstrap preserves the temporal dependence structure
#' in the residuals. The default block size follows the recommendation from
#' "Proxy SVARs: Asymptotic Theory, Bootstrap Inference, and the Effects 
#' of Income Tax Changes in the United States".
#' 
#' Both residuals and instruments are centered to preserve their sample properties.
#' For instruments, only non-zero values are centered (to handle sparse instruments).
#' 
#' @examples
#' \dontrun{
#' # Bootstrap residuals only
#' eps <- matrix(rnorm(200), 100, 2)
#' result <- fmbb_var(eps, lags = 2, BlockSize = 0)
#' eps_boot <- result$eps_boot
#' 
#' # Bootstrap residuals and instruments
#' M <- matrix(rnorm(100), 100, 1)
#' result <- fmbb_var(eps, lags = 2, BlockSize = 0, M)
#' M_boot <- result$M_boot
#' }
#' 
#' @export
fmbb_var <- function(eps, lags, BlockSize, M = NULL) {
    .Call(`_tidyMacro_fmbb_var`, eps, lags, BlockSize, M)
}

#' Remove Small-Sample Bias from VAR Coefficient Estimates
#'
#' Computes the bootstrap mean of the VAR coefficients, subtracts the bias
#' from the point estimates, and iteratively shrinks the correction towards
#' zero if the bias-corrected system is explosive (all eigenvalues of the
#' companion matrix must be strictly less than one).
#'
#' @param beta (Np+c+M) x N matrix of OLS VAR coefficient estimates
#' @param c Integer intercept indicator (1 if intercept included, 0 otherwise)
#' @param p Integer VAR lag order
#' @param boot_beta (Np+c+M) x N x nboot cube of bootstrapped VAR coefficient
#'   estimates collected from a first-pass bootstrap
#'
#' @return A list with elements:
#'   Beta: N x (Np+c+M) bias-corrected coefficient matrix (transposed
#'         relative to the input so it matches the convention used by
#'         \code{fbootstrapCholCorrected})
#'   corrections: integer count of iterative shrinkage steps applied
#'                (1 means the first attempt was already stable)
#'
#' @details
#' The bias is estimated as
#'
#'   bias = mean(boot_beta, dim=3) - beta'
#'
#' If the original estimates are already explosive the function returns the
#' uncorrected estimates.  Otherwise the function applies the full bias
#' correction and checks stability.  If the corrected system is still
#' explosive (rare in practice) it reduces the correction factor by one
#' percent per iteration until stability is achieved or 200 attempts are
#' exhausted, at which point the uncorrected estimates are returned.
#'
#' This mirrors \code{remove_bias.m} from the MATLAB reference implementation.
#'
#' @seealso \code{\link{fbootstrapCholCorrected}}, \code{\link{fcompanionMatrix}}
#'
#' @export
fremove_bias <- function(beta, c, p, boot_beta) {
    .Call(`_tidyMacro_fremove_bias`, beta, c, p, boot_beta)
}

#' Compute Wold Impulse Response Functions for VAR Model
#'
#' @param fVAR A list containing VAR estimation results with elements:
#'   \itemize{
#'     \item beta: Coefficient matrix
#'     \item c: Integer indicator for intercept (1 if intercept, 0 otherwise)
#'     \item p: Integer lag order
#'     \item n_exog: Number of exogenous variables (optional)
#'   }
#' @param horizon Integer, the IRF horizon (number of periods ahead)
#'
#' @return A 3D array (cube) of Wold impulse response functions with dimensions
#'   N x N x (horizon+1), where irfwold[,,h] contains the response at horizon h
#'
#' @details
#' This function computes the Wold (reduced-form) impulse response functions
#' for a VAR(p) model with optional exogenous variables by calculating powers 
#' of the companion matrix. The Wold IRF shows the effect of a one-unit shock 
#' to each variable on all variables in the system over time, without imposing 
#' any identifying restrictions.
#'
#' Exogenous variables do not contribute to the dynamic propagation of shocks
#' and are therefore excluded from the companion matrix representation.
#'
#' The IRFs are computed as:
#' \deqn{\Phi_h = A^h[1:N, 1:N]}
#' where A is the companion matrix and h is the horizon.
#'
#' @examples
#' \dontrun{
#' # VAR(2) model with 3 variables and 1 exogenous variable
#' y <- matrix(rnorm(200), ncol = 2)
#' exog <- matrix(rnorm(100), ncol = 1)
#' VAR <- fVAR(y, p = 2, c = 1, exog = exog)
#' irf <- fwoldIRF(VAR, horizon = 10)
#' # irf is a 2x2x11 array
#' 
#' # Plot impulse response
#' plot(irf[1, 2, ], type = "l", 
#'      main = "Response of Variable 2 to Shock in Variable 1")
#' }
#'
#' @export
fwoldIRF <- function(fVAR, horizon) {
    .Call(`_tidyMacro_fwoldIRF`, fVAR, horizon)
}

